### ISSUE TITLE
Learner Diagnostic Test

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#1]
Description: Allow learners to evaluate their own understanding and be recommended the lessons that are most appropriate for them.

Requester: Nikhil Agarwal [nikhil.agarwal.2019@gmail.com](mailto:nikhil.agarwal.2019@gmail.com)

**Web links**
- [PRD](https://docs.google.com/document/d/1GrVORe_oMrFOt6SN_JyfIr06f_TlwfwvOVMYfqT4gZY/edit#heading=h.liiqbmwmz8j8)
- [Learner facing mocks](https://docs.google.com/document/d/1gq34QOKXLV9fO3e9qXBGj4nFqpMBbwQjGhsXVQdIwbc/edit?pli=1)

**Comment by danapj** [comment]
(29 Jul) -- Chantel had requested for UX Writer to look at copy for modal description

- [x] Dana to follow up

**Comment by ghost** [comment]
Description: Allow learners to evaluate their own understanding and be recommended the lessons that are most appropriate for them.

**Comment by ghost** [comment]
@danapj Is the copy for the modal description complete/UXW approved? 
@mschanteltc Is there anything else needed here or is this complete/ready to hand off/handed off already?

**Comment by ghost** [comment]
I will review Nikhil's PR video for this tonight. https://github.com/oppia/oppia/pull/16489

**Comment by seanlip** [comment]
I think this has been handed off to devs and implemented, so closing this.
