### ISSUE TITLE
[Topic page] Add an easy link to the whole of study material 

### ISSUE THREAD

**Issue by juliafalarini** [oppia/design-team#106]
**Platform**
Oppia Web 

**Describe the request**
Add an easy link to the entire study material on the new Topic Page, in accordance with the most updated version available [here](https://www.figma.com/file/pe0Q3Zx9j6Lt9cvgC7FOOV/Practice-Session-and-Topic-Page---Project-3?type=design&node-id=1099-59863&mode=design).

**Context for the request**
For the [Redesign of Practice Session and Topic Page project](https://github.com/oppia/design-team/issues/97), we are eliminating the top tab that separates content into lessons, reviews, and practice, as these were underutilized or entirely overlooked by users. Additionally, these tabs did not allow students to correlate practices and skills with available lessons, making it unclear when they should review or practice these skills.

For the new page information architecture, it was proposed that each skill be presented after completing the necessary "N" lessons to fully introduce that skill. This way, in one place, students could study and practice the newly learned skill from the lesson.

<img width="864" alt="image" src="https://github.com/oppia/design-team/assets/92189102/f551a611-c15f-44a1-8073-f682436ff681">

However, towards the end of the design project, some stakeholders raised concerns about the need for an intuitive way to study the entire topic material. This would involve adding a user story such as "As a learner, I need an easy link to the whole study material so that I can easily study this entire subject."
Since this story was not initially covered in the PRD, it was decided to address it in a separate project. This allows for validation of whether this story is indeed a requirement for students and the design of a solution that can be properly validated by users.

**Link to PRD**
Link to the PRD [here](https://docs.google.com/document/d/1r9IEQ5z_t-eu9XAWN3eRA7iKdKuYsOQbVUjO2ZH1qKg/edit#bookmark=id.l6qpat2c0ths).

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by kmuir1991** [comment]
Hi @seanlip @liwei899  ! I'm noticing this project is high priority (whereas I don't think it was before). Is there a UXD assigned to this that perhaps just hasn't been documented in the issue?

On the UXW side, I'm considered assigning this to @Kwam98 , who has asked for more projects to work on. I don't think it's so high-level that it necessarily requires a lead to be assigned.

**Comment by seanlip** [comment]
Hi @kmuir1991 -- yup sorry, I updated the priorities recently. I think this just hasn't had a UXD assigned to it yet -- /ccing @liwei899 @rflore for info.

**Comment by stepmalt** [comment]
@dhruvmistry96 How is this going? Do you need anything from @Kwam98 on this?

**Comment by dhruvmistry96** [comment]
I am almost done with the ideation of this project. I should have the final prototype ready shortly.
Nothing needed from @Kwam98 right now.

**Comment by seanlip** [comment]
Merging this into https://github.com/oppia/design-team/issues/107 per discussion with the Web design team leads.
