### ISSUE TITLE
Multiple Oppia Classrooms (Web)

### ISSUE THREAD

**Issue by yupigummy** [oppia/design-team#109]
**Platform**
Oppia Web

**Describe the request**
UI designs for multiple pages on web (publicly available pages and learner dashboard), and help with text/descriptions for classrooms.
PM contact: @yupigummy 

**Context for the request**
We are introducing a new Science classroom for Oppia learners (and in the future, a Financial Literacy classroom) which will require additional navigation links to be added on web, a new Oppia classrooms page, and changes to the learner dashboard (dependent on the learner dashboard revamp project).

**Link to PRD**
[PRD](https://docs.google.com/document/d/1d_FUVKiHsdB8drn9ofw72mIEHztM2GAF8UhErllVMCw/edit)
[PM UI mocks](https://docs.google.com/presentation/d/1kerz0XFed-Q5gAS9VLBWmk1GtEza9hLjXrJuSDxRTlw/edit)

**Information about deadlines/priorities**
Yes this feature is time-sensitive as the Science classroom content is ready for launch, and needs to be launched together with multiple classrooms.
Target launch: Q1 2024

Note: please consider collaborating with the Android team designer on the corresponding Android issue: #125 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by stepmalt** [comment]
@S4v8n Russell said a UXW needs to be on this project. I'll be the designated UXW.

**Comment by ccc253** [comment]
@tamiorendain you are the new UXW for this project. Check out the copy in the Figma file and touch base with Kurin via email with any project questions.

**Comment by S4v8n** [comment]
@ccc253  Thank you for assigning a UXW to this project.  Just a bit of background, Stephanie already provided content for the entire project, currently this project is needing a lead from the UXW team to review for approval.  Typically, since you and Stephanie are leads, would you be able to review it for approval?  Thanks.

**Comment by ccc253** [comment]
Ah, I see! Thanks for the update @S4v8n , I'll take a look and get the content signed off.

**Comment by seanlip** [comment]
@S4v8n confirms that we have approval from design systems, UXD, and UXW, and this project has been implemented, so let's close it.

If there are any future issues, please file an issue on the tech github site https://github.com/oppia/oppia/issues so that fixes can be made. Thanks!
