### ISSUE TITLE
Credit + Team Page

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#11]
Update the design and consolidate the Team and credits page into one.

**Checklist**
- [X] L Desktop
- [X] M Tablet
- [X] S Mobile

[Designs](https://www.figma.com/file/U81n9d4jHT1S3HDAmeu4Sd/Oppia-Team%2FCredit-Page-(Diana's-Copy)?node-id=10%3A336&t=cRGN7io0VxlAqnV4-0)
[UXW](https://docs.google.com/document/d/1BmJoZwfF1QkXNGD8eFC3uklYAz45BS9wA4HDFfGhJfA/edit?usp=sharing)

**Comment by carriesdoung** [comment]
[Copy from the UXW](https://docs.google.com/document/d/1ZZ_JrxlUAynvBoQ-wC4q024CNVm5haiV3uT9c2EL0oE/edit) @danapj

**Comment by danapj** [comment]
Updating the UXW doc - https://docs.google.com/document/d/1Z1q9thrr4ms4Vv4tK3h4MrxharXW4lvz1hyaC2NxuSs/edit

**Comment by danapj** [comment]
@carriesdoung, here's the final copy I've just reviewed and made final edits on: https://docs.google.com/document/d/1BmJoZwfF1QkXNGD8eFC3uklYAz45BS9wA4HDFfGhJfA/edit?usp=sharing

**Comment by carriesdoung** [comment]
@seanlip @danapj @dchen97 hi! I just want to confirm that [this copy](https://docs.google.com/document/d/1BmJoZwfF1QkXNGD8eFC3uklYAz45BS9wA4HDFfGhJfA/edit) is final before I implement it in my mocks. Thanks!

**Comment by seanlip** [comment]
Thanks, I have taken a look at the copy and I made some suggestions, mainly to reduce the length of the text. Otherwise it LGTM!

**Comment by carriesdoung** [comment]
Here's the latest design file: 
https://www.figma.com/file/VVkr1XN32HsCNmbGmlMPn0/Oppia-Team%2FCredit-Page?node-id=336%3A385
I'm incorporating the most current design components and copy text into the file. 

After that, I think it's good for a final review from Diana + Sean.

**Comment by dchen97** [comment]
@carriesdoung - What's the status of this project? Is it ready for final review?

**Comment by dchen97** [comment]
I'll just make some final tweaks - just waiting on Carrie to give edit access. If I don't hear back in a week I'll make a copy of the file

**Comment by dchen97** [comment]
Tweaked designs and finished tablet mocks. Made some slight changes to the copy to make headlines a bit more clear and more user-focused

**Comment by dchen97** [comment]
Just need final approval from UX design and writing leads - @findimue @danapj

**Comment by ghost** [comment]
@dchen97 I don't have edit access, but I've left comments in the file.

**Comment by dchen97** [comment]
Ah I don't seem to see your comments. For reference, I had to make a [copy of the file](https://www.figma.com/file/U81n9d4jHT1S3HDAmeu4Sd/Oppia-Team%2FCredit-Page-(Diana's-Copy)?node-id=10%3A336&t=gcfSJVLveedisdMa-0) and linked to it in the original comment at the top (sorry for the confusion!). Which email would you like me to share edit access to?

**Comment by ghost** [comment]
I've added comments to your copy of the file. I don't have time to edit
today, as I'm about to leave for a short vacation. I'll be back on
Wednesday, 1/11.

**Comment by dchen97** [comment]
Thanks Mindi! Replied to all of your comments

**Comment by ghost** [comment]
@dchen97 Comments cleared and this is UXD approved!

**Comment by dchen97** [comment]
Filed an issue for development - https://github.com/oppia/oppia/issues/17421

**Comment by dchen97** [comment]
@findimue or @carriesdoung do either of you have the files for the assets used in the page? It's needed for development

**Comment by seanlip** [comment]
Closing since I believe we found another way to get the images (see https://github.com/oppia/oppia/issues/17421)
