### ISSUE TITLE
CD onboarding flow - Login/logout 

### ISSUE THREAD

**Issue by IMHieuVo** [oppia/design-team#112]
**Platform**
Oppia Web

**Describe the request**
When a logged-out user visits the contributor dashboard (CD) page at Oppia.org, they see a "you are logged out, please log in" screen. The aim of this project is to design the "you are logged out, please log in" experience for the CD.

**Context for the request**
- This functionality already exists, but hasn't really gone through a design process and should be audited. If the existing functionality is fine, it's OK to close this issue,

**Link to PRD**
N/A

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- Web projects: @ConorMack, @IMHieuVo, @liwei899 @celestinetales (UXD), @kmuir1991 (UXW), @seanlip (PM)

**Comment by seanlip** [comment]
Actually, I'm going to close this for now since it's not a major need. We can revisit later if it proves to be a problem in the onboarding process.

Please feel free to comment/reopen if you disagree with this. Thanks! /cc @IMHieuVo @rflore
