### ISSUE TITLE
CD Onboarding Flow - Guidance for CD - Translate Text

### ISSUE THREAD

**Issue by IMHieuVo** [oppia/design-team#119]
**Platform**
Oppia Web

**Describe the request**
When a new contributor visits the contributor dashboard (CD) page at Oppia.org, there is no onboarding provided. 

The aim of this project is to provide users with guidance on what the CD is for and how to use it. This particular issue focuses on guidance for **translation submitters**.

**Context for the request**
Currently, logged-in users can access the translations tab, but are provided with no onboarding on how to start translating.

**Link to PRD**
N/A

**Information about deadlines/priorities**
By breaking the project into smaller projects, we can give the developers the design quicker instead of forcing them to wait for the overall project.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by ccc253** [comment]
Updated copy for the 'Skip Dialog Box' and added some notes about the 'why' to the figma file.

**Comment by seanlip** [comment]
Thanks @rflore and @ccc253! Filed at https://github.com/oppia/oppia/issues/21062.
