### ISSUE TITLE
Partnership Page

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#12]
Description: Update the partnerships page to include pictures and descriptions of partners.

**Comment by ghost** [comment]
Next step: Input final copy and add curriculum mapping?

[https://www.figma.com/file/Wr79Z6J4KyoePAHggLHBVm/Oppia_Partner-Page_Carrie?node-id=768%3A2]

**Comment by carriesdoung** [comment]
@findimue not sure if the copy has been approved yet. 
Copy Document: https://docs.google.com/document/d/1ZZ_JrxlUAynvBoQ-wC4q024CNVm5haiV3uT9c2EL0oE/edit

**Comment by danapj** [comment]
-

**Comment by danapj** [comment]
Hi @carriesdoung @findimue I realised the previous doc linked in your comment above is not for the partnerships page. I did a little digging and found this: https://docs.google.com/document/d/1meuPc4wg7MBXynMZLt4I15V5ok1H95o1UOJAWWZtn4U/edit . Is there a more updated copy doc that you have access to? Otherwise I can just make direct comments/edits on Figma. But it seems curriculum mapping might take a while longer if it needs to be done from scratch. Let me know, thanks!

**Comment by carriesdoung** [comment]
Hi @danapj, yes, I believe this one is the correct doc. We were planning to hyperlink to the curriculum mapping in the FAQ. Please confirm with Diana about this. The Curriculum Mapping is just a spreadsheet that isn't on the document, but I think we plan to build it out into another page. Feel free to comment on the Figma file! Thanks!

**Comment by danapj** [comment]
@carriesdoung i've taken a first pass at the copy. but haven't done the curriculum mapping yet. thanks!  @rebekahnt30 will take over

**Comment by danapj** [comment]
@carriesdoung we've updated the copy on figma, let us know if that's ok!

**Comment by dchen97** [comment]
Made some tweaks to propose final design [here](https://www.figma.com/file/Wr79Z6J4KyoePAHggLHBVm/Oppia_Partner-Page_Carrie?node-id=1408%3A79&t=kSJxh0mw4GSRcoGq-0)

Just needs final approval from UX design and UX writing leads - @danapj @findimue

**Comment by dchen97** [comment]
What’s the status on getting this approved?

**Comment by ghost** [comment]
I see a couple things that need to be touched up, and I've requested Edit
Access so that I can make those minor changes.

**Comment by danapj** [comment]
I've given my thoughts on the copy in comments previously - I'm happy to edit the mocks directly after @findimue has gone over the design, if @carriesdoung could make it so that anyone can edit the file.

**Comment by ghost** [comment]
@dchen97 I duplicated the file and made a minor fix, and now this is ready to go: [https://www.figma.com/file/ZDZgUfKN8czftSSp7t4y0I/Oppia_Partner-Page_Carrie-(Copy)?node-id=768%3A2&t=pTg0ud0ROMUiNmYX-1]

**Comment by dchen97** [comment]
Submitted issue for development - https://github.com/oppia/oppia/issues/17433
