### ISSUE TITLE
Multiple Classrooms (Android)

### ISSUE THREAD

**Issue by moewastaken** [oppia/design-team#125]
**Platform**
Oppia Android

**Describe the request**
Require UI designs based on the PRD to enable multiple classrooms in the Oppia App.

**Context for the request**
This is a new feature.   Currently, app learners are limited to a single subject (math).  "Classrooms" will allow the development and consumption of content across multiple subjects.  Please see the PRD for details.

**Link to PRD**
https://docs.google.com/document/d/1uOiDnWBxJmDMwqej-VSRKEnDP4Been3np9y1ov6YTNA/edit#heading=h.liiqbmwmz8j8

**Information about deadlines/priorities**

Targeted for design completion by Q1 2024.

Note: please consider collaborating with the Android team designer on the corresponding Android issue: #109 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD:  @GlowWindow (for Android projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by aayush0982** [comment]
@seanlip Could you please confirm whether this matter involves any coding? If not, may I kindly request to be assigned to handle it?

**Comment by seanlip** [comment]
@aayush0982 The designs aren't created yet so this isn't ready for coding. If you are looking for Android projects, please see github.com/oppia/oppia-android instead.

**Comment by aayush0982** [comment]
@seanlip No I mean if it is not related to coding , can you assign this to me?

**Comment by aayush0982** [comment]
@seanlip just I need to know more clearly about teacher part in app 
As I have downloaded the app and understand what you want for a student

**Comment by aayush0982** [comment]
@seanlip but as I  tried to set up profile as a teacher , I don't found any option so please tell that if this app contain profile for teacher or I have to create design for it, if this project will be assigned to me

**Comment by seanlip** [comment]
Hi @aayush0982, design issues are only available to be taken by members of the design team. If you would like to apply for non-coding volunteer positions at Oppia, please fill in the form at www.oppia.org/volunteer . Thanks.

**Comment by aayush0982** [comment]
Hi @seanlip  , 
I wanted to bring to your attention that I have completed the form as instructed earlier; however, I haven't received a response yet. Could you please take a moment to look into this matter?

**Comment by seanlip** [comment]
@aayush0982 I'll connect you with Angie, our volunteer coordinator, who can follow up.

**Comment by aayush0982** [comment]
@seanlip 
Ok

**Comment by seanlip** [comment]
Current Figma file: https://www.figma.com/file/l3wNKY9RkBhwHcydNqZn4Z/Oppia-Multiple-Classroom-Android?type=design&node-id=0%3A1&mode=design&t=oTn1pm8cTJd1a5CW-1

**Comment by ashley-ya** [comment]
[design decision notes]
from meeting yesterday, design decision surrounding multiple classroom layout pattern was driven by a focus on minimizing the amount of classrooms a user could look at at once. The bulk of the users attention would be on looking at the classroom topics anyway.

**Comment by ashley-ya** [comment]
Hi, looking to verify a new design style with the design systems team.

@qluuu and @celestinetales, I want to have a darker background for the selected tab options and am proposing we use darker shades for the card text and card background. [screenshot attached]

when looking at the design style guide, we don't appear to have an existing style for this type of card. let me know if my proposal is alright or if i need to align the style to something else. the changes to the background color and text color help differentiate the selected tab state, and also provide WCAG AAA accessibility.

reference material:
https://www.figma.com/design/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?node-id=2-8412&t=kpjeAoNUVacwWgBM-1

<img width="914" alt="Screenshot 2024-07-03 at 10 16 20 AM" src="https://github.com/oppia/design-team/assets/67245252/9035e380-b7bf-4f5e-998a-928b728e32f1">

**Comment by qluuu** [comment]
Thanks for reaching out @ashley-ya I definitely agree with you that the darker color would aid in accessibility. As a food for thought, will you be considering the use of bolding the text as a secondary indicator for highlighting the tab? 

As for the android style guidance, I think it would be good to add to the design system in a formal way. Please create an annotation on your figma file with a note on use cases and guidance. During your handoff phase, please kindly flag the design system team in your communications to ensure that it gets added to the file. 

(We are still in the process of developing a good 'way of working' to ensure that new changes get added to the design system.) I think this is a conversation that we can sync on between the design systems team and the android team. Let me know your thoughts. :)

**Comment by ashley-ya** [comment]
@qluuu  thanks for the feedback! I agree, I think a closer collaboration between the design systems and android team can be a great experience for both teams! I was thinking about trying to change the font weight as well, but the font we are using only has one weight setting. 

Will make sure to set up a hand off between designs systems once these designs are finalized.

**Comment by ashley-ya** [comment]
Hi @qluuu, @celestinetales, do we have a file for mobile dark mode patterns? I'll be adding a pattern in dark mode as well. I've already let the developer know that these are final and ready to be implemented .

Here's my figma file with the new design patterns and SVG assets, let me know if you want to have a quick chat to discuss:
https://www.figma.com/design/H4BaHlwnALtjQcemP322hE/Oppia-Multiple-Classroom-Android-(Ashley's-Expansion)?node-id=0-1&t=OgBMYYeRmCq6hy80-1

**Comment by qluuu** [comment]
Hi @ashley-ya I know android has a dark mode, but I don't think it was ever recorded into the design system file (before my time at Oppia), but now would definitely be a good time to start adding to the file. Can you put together a frame with information on dark mode colors and description on use cases? You can include this as a separate page on your figma if you would like with a title like 'handoff to design system'.

Currently, we are still trying to work out a system to record this information. In the past, android design system and web design system were separated. As android lead and as a UX designer in general, what do you think of this? Would your team prefer to have a design system file that is unique to android or refer to a centralized design system with a section for web and a section for android?

**Comment by ashley-ya** [comment]
Hi @qluuu, this sounds like a wonderful opportunity to partner with someone from the design systems team to start documenting use cases for dark mode. Is there someone on the design systems team that would like to lead this task? It actually sounds like it might be the start to a much larger project; of documenting and creating guidelines for the dark mode version. I can meet with them on a 1:1 meeting to discuss the pattern I've created and make sure im documenting things correctly. I've given a description on what my new pattern is, but im not sure if this is the format/detail needed.

I also wasn't around when the dark mode was first introduced, so more information on dark mode would require a chat with developers to get you the full color palette and where it shows up. One of the devs on this project mentioned that they didn't have access to any dark mode figma files, so im not sure how the color palette came to be. There are some colors on my dark mode screens that I haven't verified yet, so aside from the pattern I created I'm not sure the exact colors used.

As far as combining the design systems, I think it would require a longer discussion to delve into the use cases, user needs, and effort involved in combining the systems. I'm not too familiar with the web design system so I'm not sure how much they differ. I would propose we schedule a call to discuss this more in depth!

**Comment by ashley-ya** [comment]
Hi @stepmalt @seanlip @qluuu , the designs are ready for final sign off. 

Stephanie, I'm not sure if you already had conversations regarding the writing for these screens, but no changes were made to the writing since I started!

https://www.figma.com/design/H4BaHlwnALtjQcemP322hE/Oppia-Multiple-Classroom-Android-(Ashley's-Expansion)?node-id=0-1&t=OgBMYYeRmCq6hy80-1

**Comment by seanlip** [comment]
The [final mocks](https://www.figma.com/design/H4BaHlwnALtjQcemP322hE/Oppia-Multiple-Classroom-Android-(Ashley's-Expansion)?node-id=3064-11726&node-type=canvas&t=a5smLYaOhvvUdVrZ-0) here look great, thanks @ashley-ya! The feature has been implemented in https://github.com/oppia/oppia-android/issues/5344 so I am closing this issue as completed.
