### ISSUE TITLE
Add compelling pages for Oppia website (Web)

### ISSUE THREAD

**Issue by melhikh** [oppia/design-team#127]
**Platform**
Oppia Web

**Describe the request**
Add compelling pages for “About” with a CTA of volunteer/donate/partner, 'Volunteer', and 'For Parents/Teachers' pages.

**Context for the request**
The current pages content are **not** UpToDate, engaging, and fulfill all information requested from their target audiences. These problems and the information that must be provided, had been determined through a user research.

Link to PRD (Status: **In progress**)
[PRD](https://docs.google.com/document/d/1enceUlqh7KpaE5i_rdKE-0mZh899tYNf524vFiUYZvI/edit#heading=h.rpq25vez37fp)
Links to mockups (Status: **In progress**)
[UI mock for About, Volunteer, and For Parents/Teachers pages](https://www.figma.com/file/A40Whr8Pmbc5ZlOwMDjXn4/Compelling-Informational-pages?type=design&node-id=3-48659&mode=design&t=gkPLKdbAYu52sS1H-0)

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by kmuir1991** [comment]
FYI, I'm adding @laranowak to this issue to work on the associated document: https://docs.google.com/document/d/1QamlYvT0RZydn90uws5ZHKqvJ-up4g2iLK-xB5xn7aU/edit#heading=h.mzyciinwveg9

**Comment by stepmalt** [comment]
@laranowak @melhikh checking in - how is this project going?

**Comment by stepmalt** [comment]
@melhikh Do you need a new UXW on this? Lara is no longer on the team. Let me know, so I can get this assigned.

**Comment by melhikh** [comment]
Hi Stephanie,

I think I might need you to see a thing or two. Can I email you directly
with the things that I want you to check?

Best,
Melhik

**Comment by stepmalt** [comment]
@melhikh You never need to ask, email me any time! Always welcome!

**Comment by melhikh** [comment]
Great!

**Comment by seanlip** [comment]
Closing this since it's completed and implemented -- thanks @melhikh !
