### ISSUE TITLE
Learner Group - Facilitator Side

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#13]
**Description**
be able to finish mock for desktop version by 1st July, both mobile and desktop version by 10th, and hand off to engineers.

**Web links**
- [Group MVP doc](https://docs.google.com/document/d/11bPIKXHyyeI2WTF4Ujk_4TjPw65TVv-7SAlD8mJZ65U/edit?usp=sharing)
- [PRD](https://docs.google.com/document/d/1GMkU_Vxi7Y69ZI4gRfxLaDpX-sWfaMZsGQdXasdeELQ/edit#heading=h.4xe0dz7wpghp)

**Checklist**
- Responsive Designs
  - [ ] XL Desktop
  - [ ] M Tablet
  - [ ] S Mobile

**Comment by seanlip** [comment]
(From Carrie)

Hi @ cwg421 thanks for letting us know!

**Comment by danapj** [comment]
- [x] By 10 Jul -- Dana to add copy for web mocks 
- [ ] August -- Dana to add copy for mobile mocks (in Figma comments)

**Comment by ningz2** [comment]
The facilitator's part has been handed off to engineers and implemented. But some UI elements and wording still need to be polished up.

The learner's part only has a mid-fidelity version for the desktop view for now. The high-fidelity design for both desktop and mobile versions is requested in September.

**Comment by fionafyzeng** [comment]
@ningz2 will update checklist by EOD

COA: Meeting to take place on SEP 22 to discuss next steps.

**Comment by ningz2** [comment]
Facilitator Part:

90% desktop version
90% mobile version

Learner Part:

- [ ] desktop version
- [ ] mobile version

The tablet version TBD

**Comment by danapj** [comment]
hi @ningz2 could i have an update on which mocks require finessing on the copy?

**Comment by ningz2** [comment]
> 

Hi Dana, thanks for asking. No rush for now. We are now focusing on the learner part of this project. 
Mindy may contact you if she needs help with the content.
