### ISSUE TITLE
Typography: Transfer Over Tokens & Update Guidelines

### ISSUE THREAD

**Issue by qluuu** [oppia/design-team#130]
**Platform**
Oppia Web | Oppia Android

**Describe the request**
Filling in tokens for **typography** in the design system template. Drawing from the existing Oppia design system files from on-boarding files and Project 2, combine, refine and update typography guidelines. This will be used as a starting point to further analyze and solve deeper design system issues.

**Context for the request**
This is a new initiative to update, improve, and maintain Oppia's design system to meet UX designer needs.

**What is the broader user journey that this feature fits into?**
This issue lies in the designer's journey of struggling or wasting time finding the correct asset efficiently.

**What is the current user experience like (where is the user located before they encounter this feature)?** Feel free to add screenshots.
Designer can reference and grab assets from:
-  [Project 2](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design&t=zLmFsjizv3mGPtoy-0)
- [On-boarding Figma Design Guide (Web)](https://www.figma.com/file/STgAK3PxJz3qxoljrTPy2U/Web-Style-Guide-%3E-2023-%3E-Aug?type=design&node-id=0%3A1&mode=design&t=Tc16GaBg5KWPo0te-1)
- [On-boarding Figma Design Guide (Android)](https://www.figma.com/file/G0jHrMaopFzk2ZksuynBjS/Android-style-guide?type=design&node-id=0%3A1&mode=design&t=2KmB8FXz89klrsZI-1)
- Look at the current products (web/mobile)
- Or, grab from other projects that may have a solution.

**Link to Oppia Design Systems Template**
[Oppia Design Systems Figma File](https://www.figma.com/file/MOnLoR43wqVrxjBrN8oKj1/Oppia-Design-System-Template?type=design&node-id=32172%3A850&mode=design&t=m5Ot7gVQOLsvB9Ox-1)

**Information about deadlines/priorities**
This can be tackled at the usual priority.

DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.

- [x]  UX Design System (UXDS) approved
- [x]  UX Writing (UXW) approved
- [ ]  Product approved

For a design system project to be completed, it needs approval from UXDS, UXW, and PM. Please tag the following reviewers when your project is ready (it's enough to have one sign-off from each of UXDS, UXW and PM):

Design System projects: @celestinetales / @qluuu (UXD), @seanlip (PM)
LaCE projects: @ConorMack (UXD), @jikim322 / @roxanashirazi (UXW), @seanlip (PM)
CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @seanlip (PM)
Android projects: @kaiyuxu (UXD), @jlevick (UXW), @seanlip (PM)

**Comment by kmuir1991** [comment]
Hi @qluuu ! Just wanted to let you know I've left comments on the typography page. Pretty much everything is to ensure that all components are sentence case, since nothing I saw warrants the use of title case, all caps, etc. Thanks!

**Comment by qluuu** [comment]
Hi @kmuir1991 ! Thanks for going through the page and for the comments, I really appreciated. 

I did some editing and added "Type: Sentence case" in the tables for more clarity as well as going through each style to check. I left some comments in response to yours to confirm changes. 

There are a couple that I do want to double check with you. tl;dr - it's mainly Nav Bar Heading and Footer Heading being all caps, Footer text being Title Case, and Card Headings being Title Case in the current website. So, I just wanted to confirm that these are ok as is or if sentence case is the new standard that hasn't been implemented across all aspects of the website yet. 

(Lastly, feel free to resolve any of the "Confirm changes" comments once you've read them!) Thanks again :)

**Comment by kmuir1991** [comment]
Hi @qluuu ! Thanks for going over those comments.

Yes, I think we should additionally be avoiding all caps in addition to title case and italics. The reason being is the same for all: it negatively affects readability and results in an unnecessary cognitive load on the user.

For things that were previously all caps, title case, etc, we should make those sentence case moving forward. It should be okay that these changes don't necessarily reflect every part of the website, which in the future could probably use an audit for copy consistency. I've spoken with @seanlip about this and he seems to be on board with this (but tagging him here just in case I'm wrong)

**Comment by qluuu** [comment]
Hi @kmuir1991 Great thanks for your quick reply. Sounds good! 

I've made some edits to the file and adjusted styles to sentence case and replied to your question on the figma file (tl;dr the tool tip button style is indeed underline because it is a link).

Re: Future audit for copy consistency, I agree. It's a really good idea going forward!

**Comment by seanlip** [comment]
Yup confirming that the design style guide should be based more on "what we think of as the ideal state for the website" rather than conformance with what's currently implemented.

As we firm up desired styling we can file issues on the web developers' github to do the standardization.

**Comment by seanlip** [comment]
Hi @qluuu Just to check, for this project, is any follow-up work needed on the Web or Android side? Or is this targeted only at the design guides and nothing else?

Thanks!

**Comment by qluuu** [comment]
Hi @seanlip Just confirming that this is targeted at only design guides, no outstanding updates needed for any Web or Android projects. Thanks!

**Comment by seanlip** [comment]
OK, thanks -- then I think we can close this as completed. Thanks @qluuu!
