### ISSUE TITLE
Checkpoints (follow-up work)

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#14]
Enable learners to stop before finishing a lesson and pick up where they left off later.

(Note: base design is implemented, but there is follow-up work.)

**Responsive Designs**
- [ ] XL Desktop
- [ ] M Tablet
- [ ] S Mobile

**Comment by ningz2** [comment]
UI needs to be polished up. The project is currently on pause and will resume in late September.

**Comment by ningz2** [comment]
- [ ] - Update the margin/padding/buttons/icons to the current design, finish up the design for lesson card and incorporate into the design guide if necessary
- [ ] - Coordinate with Rio for the Topic page design
- [ ] - Coordinate and confirm with UX writing team for re-phrasing (resume lesson modal) and terminologies 
- [x] - Save the current design for lesson info button and modals for now, we can wait until having a better understanding of the user flows and information architecture
- [ ] - Need confirmation for the design of Localization project and how to incorporate options in lesson card design
- [ ] - Next step after this project: standardize the spec for the white background box and background graphics across all site pages

**Comment by ningz2** [comment]
- Update the margin/padding/buttons/icons to the current design, finish up the design for lesson card and incorporate into the design guide if necessary _(To-be-reviewd)_
 - Coordinate with Rio for the Topic page design _(In-progress)_
 - Coordinate and confirm with UX writing team for re-phrasing (resume lesson modal) and terminologies _(Ready for review, will contact after Christmas)_
 - Save the current design for lesson info button and modals for now, we can wait until having a better understanding of the user flows and information architecture _(Next step after this project?)_
 - Need confirmation for the design of Localization project and how to incorporate options in lesson card design _(to-do)_
 - Next step after this project: standardize the spec for the white background box and background graphics across all site pages _(to-request-update in the Design System)_

**Comment by ningz2** [comment]
- The topic page (lesson list page) is finished with Rio. Waiting for Diana to review
- Waiting for UXW response on the workflow
- Waiting for Julia's response to confirm the updates for the localization project.

**Comment by ghost** [comment]
@dchen97 @danapj @juliafalarini See @ningz2 last comments and please reply with any updates. Thank you!

**Comment by ghost** [comment]
@ningz2 Could you write out a list of what you're wanting to follow-up with still on this project, please?

**Comment by ningz2** [comment]
> @ningz2 Could you write out a list of what you're wanting to follow-up with still on this project, please?

- The popover window showing the user's current progress needs review from UXW (Roxana Shirazi)
- The "Previous Answers" feature could be saved to a separate file.
- The lesson info modal needs adjustments on the UI details this week.

**Comment by juliafalarini** [comment]
Working on it! I'll get back soon with updates.

**Comment by ningz2** [comment]
- The lesson page is revised based on Dana's comments on Rio's file. 
- Roxana left comments today for revision.

**Comment by ningz2** [comment]
Complete:
- Web UI fixed based on comments from Roxana.

To do:
- Confirm with Diana about tags (keywords?) on the info modal
- Start revising Mobile UI

**Comment by ningz2** [comment]
Separate project file for "Previous Answers"
[https://www.figma.com/file/4usECEMqKPJ0nXPkrC94AQ/Previous-Answers?node-id=0%3A1&t=9RA8uhWWPACEqYr0-1](url)
(Due to the free account limit, this is a Figma draft file. Please make a copy to start new edit)

**Comment by ningz2** [comment]
Separate project file for "Keywords/Tags"
[https://www.figma.com/file/mAlV7Bar1OLitvhRmci6yy/Keywords%2FTags?node-id=0%3A1&t=WBhVnDGSMP9GoSUC-1](url)
(Due to the free account limit, this is a Figma draft file. Please make a copy to start new edit)

**Comment by ghost** [comment]
@sarahking22 @dchen97 Ning's last two posts are files she started for features that she thought might need work in the future. I'm not sure if you want to convert them into their own issues or just save the links somewhere for future reference. When you decide that, this issue can be closed as complete, I believe.

**Comment by seanlip** [comment]
@dchen97 Please see Mindi's last comment. Could you please move this issue forward appropriately? Thanks!

**Comment by dchen97** [comment]
What is the final design link for this issue?

**Comment by dchen97** [comment]
Filed [issue](https://github.com/oppia/oppia/issues/18385) for previous answers

**Comment by dchen97** [comment]
I think keywords/tags will be addressed with @juliafalarini's project to redesign the lesson player

**Comment by ningz2** [comment]
> What is the final design link for this issue?

@dchen97 
Final Design: https://www.figma.com/file/NRJaGClL9EUJBAhugi4oPQ/Oppia-User-Checkpoints?type=design&node-id=430%3A65&t=ff4b5xAW0uAWmAM5-1
We are in the process running an A/B test for lesson card button options.

**Comment by seanlip** [comment]
Hi folks -- I checked with @dchen97 and she is kind of confused about what exactly the status of this is and whether it's ready to be handed off to developers.

@ConorMack @rfinch11 @ningz2 I'm moving this back to the main board for now (it used to be in "handed over to PM" stage). Would it be possible to clarify the above, please? Feel free to close this issue and make a new one if that would be easier. Thanks!

**Comment by ningz2** [comment]
> Hi folks -- I checked with @dchen97 and she is kind of confused about what exactly the status of this is and whether it's ready to be handed off to developers.
> 
> @ConorMack @rfinch11 @ningz2 I'm moving this back to the main board for now (it used to be in "handed over to PM" stage). Would it be possible to clarify the above, please? Feel free to close this issue and make a new one if that would be easier. Thanks!

Hi @seanlip and @dchen97 ,

As we discussed, this project was split into several parts:

**User Checkpoints:**

1. Confirm the Lesson List page (the UXW team is working on the A/B test now. Once the test is done, this part will be ready to hand off)
2. Need to rethink about showing the progress bar and visualizing checkpoints in a better way and at the right spot along the user flow. (thinking about showing progress bar directly on the lesson pages instead of hidden on the lesson info modal, this part will be the next step for the Checkpoints project)

**Previsou Answers** and **Key words/Tags on the lesson info modal**

- These tasks became separate projects, as linked above in this thread.

**Comment by seanlip** [comment]
Thanks @ningz2. Just to confirm then, it sounds like none of the parts are fully ready to hand off to developers yet, right?

Given what you say, I assume there should be 3 issues in the [LaCE design tracker]( https://github.com/orgs/oppia/projects/7/views/4) (one for each sub-project), right? If so, I suggest working with @ConorMack @rfinch11 to create those, and we can then close this issue.

**Comment by ningz2** [comment]
> Thanks @ningz2. Just to confirm then, it sounds like none of the parts are fully ready to hand off to developers yet, right?
> 
> Given what you say, I assume there should be 3 issues in the [LaCE design tracker](https://github.com/orgs/oppia/projects/7/views/4) (one for each sub-project), right? If so, I suggest working with @ConorMack @rfinch11 to create those, and we can then close this issue.

@seanlip Correct, none of them are ready now, but the lesson list page should be ready soon.
There should be three issues:

- User Checkpoints (phase 1: lesson list page; phase 2: progress bar improvement)
- Previous Answers
- Key Words/Tags on Lesson Info Modal

**Comment by seanlip** [comment]
@ningz2 @juliafalarini and I just had a discussion on this. The outcome is that no further work is needed for the last two issues mentioned in the previous comment. @ningz2 will file an issue for the first one (user checkpoints).

Closing this issue in the meantime.
