### ISSUE TITLE
Audit the Android style guide and update it to match the app.

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#156]
- [x] Identify any discrepancies -- make a list and confirm those 
- [x] Update current components in file and update the general layout to match the planned design of the app. (For Topic screen: info tab is gone; keep the others.)

**Comment by seanlip** [comment]
Note: @ashley-ya has completed the first part. See 
https://www.figma.com/design/P9nDyz9EsKF4S7SgmtO7YR/Android-style-guide-(Copy)?node-id=2-8412&t=bXAlDoWvzjvoDX5H-1 for the design file.

Next step is to fix the issues and publish the new guide.

**Comment by seanlip** [comment]
Plan going forward (discussed with @ashley-ya on 6 Nov 2024):

- Do the remaining tasks that are quick to do (under 30 min)
- Leave a comment on this issue enumerating all the other tasks, in a list. We'll come back to this issue and pick them up later.

**Comment by ashley-ya** [comment]
updated file: https://www.figma.com/design/ijIhR6rxg1e9EOCTcSP9T3/Oppia-Manesh?node-id=106-29879&t=wUB8s13T1dbm1ubI-1

**Comment by seanlip** [comment]
Closing as completed. Thanks @ashley-ya!
