### ISSUE TITLE
Address issues with missing Android design system components

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#158]
![Image](https://github.com/user-attachments/assets/9814ef3a-00f1-43ed-8ad4-a3006c1af1bb)

- The progress bar doesn't match the design system. 
- The icon next to '1' (circle with 3 dots) cannot be found in design system "current state" as well as the lock symbol next to each number. 
- The icon above "revision" does not match the one in the design system icons labeled "icon - practice".
@lmahon90 

![Image](https://github.com/user-attachments/assets/9d04b5a1-7574-4ba6-ac81-5a0aa5723ee0)

- Buttons in this image cannot be found in design system components. I've had to recreate something similar for my current mockup. The left arrow icon in the button does not exist.

**Comment by ashley-ya** [comment]
created new play back icon, added option for right-side icon in buttons, and updated the storycard
https://www.figma.com/design/ijIhR6rxg1e9EOCTcSP9T3/Oppia-Manesh?node-id=108-12056&t=wUB8s13T1dbm1ubI-1

**Comment by seanlip** [comment]
Closing as completed. Thanks @ashley-ya!
