### ISSUE TITLE
Lesson Completion Screen

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#2]
**Requester**: Vishnu Nithin Reddy [nitinreddy226@gmail.com](mailto:nitinreddy226@gmail.com)

**Web Links**:
- [Figma Mock](https://www.figma.com/file/pRDxAiJE7HpcYtKsLu42Ax/Lesson-Completion-Screen?node-id=0%3A1)

**Comment by ghost** [comment]
@seanlip Not sure what this is -- just has Figma Mock link, no PRD. Is this complete?

**Comment by seanlip** [comment]
Yeah, I think this is complete -- at least I don't think it's an active to-be-designed project any longer. Closing, thanks!
