### ISSUE TITLE
Web language picker unification, Fallback behaviour when a lesson is not available in the selected language [Web only]

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#21]
**Checklist**
- Responsive Designs
  - [ ] XL Desktop
  - [ ] M Tablet
  - [ ] S Mobile

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by ghost** [comment]
@seanlip @dchen97 Is there a PRD for this request?

**Comment by seanlip** [comment]
Sorry, need to defer to @dchen97 for this one.

**Comment by dchen97** [comment]
https://docs.google.com/document/d/1lfx8y12kuP0m9xylG_ju0K2ITIrnVkJqx8BhVsnGXHo/edit

**Comment by ghost** [comment]
Email Julia to see where progress is on this and what can be assigned.

**Comment by ghost** [comment]
@juliafalarini Hi, Julia, can you leave a comment to update where you are on this project, please?

**Comment by Ronnie-Mercy** [comment]
Hi Mindi, id like to schedule a meeting concerning this issue you assigned
to me as I'm not really clear on it, when would you be available?

Thanks,
Ronnie.

**Comment by ghost** [comment]
Hi, Ronnie, 

Yes, we’ll meet on this soon. We may need to coordinate with the designer who’s been working on this prior to now to see what’s left to be wrapped up. Please give me a few days to get that sorted.

Thanks,
Mindi

**Comment by ghost** [comment]
@juliafalarini Is there work that still needs to be done on this project, and if so, when can you meet to discuss it? Thanks!

**Comment by juliafalarini** [comment]
Hi @findimue sorry for the delay! It's been a while since I've worked on this project, so a meeting to go over the remaining steps would be very helpful. My time zone is -3UTC (Brazilian time), I think you might be PST, so I would like to ask if we can schedule this meeting until 21:00 at the latest, Brazilian time. Thanks!

**Comment by ghost** [comment]
I will work on scheduling a meeting soon!

**Comment by ghost** [comment]
I’ve scheduled a meeting for Friday, 2/10, at noon Pacific time/5pm in your time zone, I believe. Will that work for you?

**Comment by Ronnie-Mercy** [comment]
Hi, yes. Okay with that. See you by 5pm on Friday.

**Comment by juliafalarini** [comment]
I'm incorporating these tasks inside of the new onboarding experience. @sarahking22 I don't think we have a issue created for the new [Web Onboarding experience](https://docs.google.com/document/d/1r91ypya5HasdGsuLcuzt_utKik6xpIVe9koYGynl6kg/edit#).

**Comment by juliafalarini** [comment]
[Submitted Reports for Web Improvements Research - Spreadsheet](https://docs.google.com/spreadsheets/d/1BNkynOkA4H_uEIFwf9-6qFJYhcxfFU8cfuXZgI3UetQ/edit?usp=sharing)

**Comment by juliafalarini** [comment]
Consolidating the tests results [here](https://docs.google.com/spreadsheets/d/18Hyoy2yWgAsgAKVCt1lTVd8DajGu1vM4YIAdqme_tLQ/edit?usp=sharing). @dchen97 has reviewed it. Waiting for @sarahking22 to find a time to meet and discuss it.

**Comment by dchen97** [comment]
Removing raising discoveraibility to be part of new web onboarding experience ticket

**Comment by dchen97** [comment]
@juliafalarini your current designs don't seem to encompass web language unification and fallback behavior so I'm deassigning you from this ticket for now

**Comment by seanlip** [comment]
Per @juliafalarini, this is superseded by:
- the lesson player project, #58 (since users don't have to select a language to start a lesson anymore, and the lesson will already be in their preferred language)
- #97 (since the "fallback behavior for when a lesson is not available" is being tackled differently from what's proposed in the PRD -- instead of showing them a dialog letting them know that that lesson is not available, they will select a secondary language directly on the topic page, through a dropdown, before entering the lesson).

So, closing this issue.
