### ISSUE TITLE
Fallback behaviour when a lesson is not available in the selected language

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#22]
**Checklist**
- Responsive Designs
  - [ ] XL Desktop
  - [ ] M Tablet
  - [ ] S Mobile

**Comment by dchen97** [comment]
PRD: https://docs.google.com/document/d/1lfx8y12kuP0m9xylG_ju0K2ITIrnVkJqx8BhVsnGXHo/edit

**Comment by ghost** [comment]
@cwg421 Hi, Chloe! Is this a project you have room to take on right now?

**Comment by seanlip** [comment]
I don't think Chloe is working on this; deassigning.

Also this seems to overlap with #21 (and references the same PRD) so I'm going to close it.
