### ISSUE TITLE
Raising discoverability of language selection on the web [Web only]

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#23]
**Checklist**
- Responsive Designs
  - [ ] XL Desktop
  - [ ] M Tablet
  - [ ] S Mobile

**Comment by dchen97** [comment]
PRD: https://docs.google.com/document/d/1lfx8y12kuP0m9xylG_ju0K2ITIrnVkJqx8BhVsnGXHo/edit

**Comment by ghost** [comment]
https://www.figma.com/file/u4Q5gkhBh5plFKUxtxY7KZ/Localization-project?t=zfo3BkmaRhs7V1tf-0

**Comment by juliafalarini** [comment]
This has been addressed in the [Web Onboarding project](https://github.com/orgs/oppia/projects/7/views/4?pane=issue&itemId=24309264), check it [here](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6727-476971&mode=design&t=1v7gpuG0d8yMQxcw-4).

**Comment by seanlip** [comment]
Thanks @juliafalarini! Closing this issue as done, then.
