### ISSUE TITLE
Lesson Search

### ISSUE THREAD

**Issue by carriesdoung** [oppia/design-team#29]
Learners and teachers have difficulties finding the right lesson that fits their/the students level and need with current lesson search experience. This PRD proposes improvements for the learners’ and teachers’ lesson search experience

[PRD](https://docs.google.com/document/d/118pZ_BSse-YBFIqFjQDrhq1_Hk-VlpjqYWm980aBFEc/edit?usp=sharing)
Figma [https://www.figma.com/file/1Rosc1GnZhmwaKYPifH19w/Lessons-Search-Improvement?node-id=12%3A131](https://www.figma.com/file/1Rosc1GnZhmwaKYPifH19w/Lessons-Search-Improvement?type=design&node-id=1506-17079&mode=design&t=VzAdil6G5pyj32Yq-0)

[User Research Plan](https://docs.google.com/document/d/1B2v3OIuD3ibQmbSJbXv0Grv1ZYTq2YttWWyyDX341po/edit)

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by RioChanHY** [comment]
A clickable file is created but still has minor technical issues that need to work on

**Comment by RioChanHY** [comment]
The fully clickable file passed to my PM(May)

**Comment by RioChanHY** [comment]
Contacted Julia about the front page redesign feedback
Made the decisions on the front page and the search filter with PM (May)

**Comment by jikim322** [comment]
For UXW there's just one outstanding item about the label for the search bar on the desktop version. We made some notes but weren't sure if any additional changes were going to be made. I'll leave a comment in Figma.

**Comment by rfinch11** [comment]
@jikim322 I just replied in figma with my thoughts about the label. If you are Ok with the recommendation, then can you sign off on the project? Otherwise let's discuss further.

**Comment by jikim322** [comment]
Comment makes sense! UXW approved

**Comment by seanlip** [comment]
@RioChanHY I just did the product review, sorry it took a while. There are a couple of comments on the mocks that still need to be addressed. Could you please address them?

Also, would it be possible to make a separate page in the Figma file with just the final mocks for developers? That way, I can point them to that page and they won't be confused about what to look at.

Thanks!

**Comment by seanlip** [comment]
( @RioChanHY @rfinch11 @ConorMack -- moving back to "in progress", please move this back to "Handed off to PM" once the mocks are finalized. Thanks!)

**Comment by seanlip** [comment]
Hi @ConorMack, I'm about to file this on the technical GitHub, but I don't understand why this was moved back to the "Handed off to PM" board. The relevant mocks to hand off are supposed to be the ones in the "Update after user report", but there are open comments there that are not addressed. So I am sending it back to the design team.

@RioChanHY @roxanashirazi Would you be able to take a look and address the final comments, please?

Also, @RioChanHY, could you please put the final implementable design in its own page in the Figma file so that developers know which one to follow on?

/cc @liwei899 too in case she can help with this, and @S4v8n since he's working on a related project and it might perhaps make sense to merge both of them instead. Thanks!

**Comment by S4v8n** [comment]
@seanlip Let me know if you want me to merge the two projects together.  I think it makes sense to merge them.  :)

**Comment by seanlip** [comment]
Yup, let's please merge them. Thanks!

(To do that, copy anything relevant from here into the issue thread of the project you're working on, and update the description of the other thread. Then, leave a note on this issue saying that it has been merged into that other issue, linking to that issue thread from here. Then we can close this issue.)

**Comment by S4v8n** [comment]
@seanlip Sounds good.

**Comment by S4v8n** [comment]
This project has been merged with[ Issue #85 - Search bar navigation](https://github.com/oppia/design-team/issues/85). Please go to this link to view new updates on the project.

**Comment by seanlip** [comment]
Thanks @S4v8n, closing this since it's now tracked in #85.  Thanks!
