### ISSUE TITLE
Making Question Submission Workflow better on mobile

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#3]
**Requester**: Harshvardhan Singh [sharshvardhan101@gmail.com](mailto:sharshvardhan101@gmail.com)

Web Links:
- [With Question Submission workflow](https://www.figma.com/file/gpS0ZJhT1KWrjwWrY9Ow3T/Contributor-Dashboard---With-Question-Submission-Workflow?node-id=0%3A1)

**Comment by ghost** [comment]
Email Harshvardhan and ask about status of this request.

**Comment by seanlip** [comment]
Actually, this isn't currently active. Closing this; we can reopen a new issue if the need arises.
