### ISSUE TITLE
Beta Notice for Practice Questions

### ISSUE THREAD

**Issue by danapj** [oppia/design-team#30]
Task: Write copy for beta notice for practice questions launch, to let users know: (a) the practice questions feature is in beta; and (b) it's only available in English for now. 

Doc: https://docs.google.com/document/d/14EJ2p-JSAJKbu4TyII4ZEeMIpwG_zf8zhShOokvlWuA/edit

**Next milestone:** Dana needs to address Sean/Diana's comments

**Comment by danapj** [comment]
21 Aug - Waiting on a reply on the UXD element from @fionafyzeng @findimue

**Comment by ghost** [comment]
21 Aug - Replied to @danapj adding in @carriesdoung for her input

**Comment by fionafyzeng** [comment]
24 Aug - FZ replied to @danapj about the tooltip element.

> Tooltip, "This feature is only available in English for now"
> 1. Too tiny.
> 2. Unnecessary, since there will be an Android Beta Launch landing page where they'll see all the info regarding available languages.
> 3. Tooltip for the "Beta" bookmark icon is tmi.

**Comment by danapj** [comment]
29 Aug - @fionafyzeng i don't have strong opinions about the tooltip, but wanted to give you some context: we still want people to know that it's beta **while** they are on the practice questions feature, and what beta means in this context. if we drop the tooltip, do you have other suggestions to express this? 

also to clarify on point 2 -- this isn't related to the android beta launch! this is for the beta launch of the practice questions feature.

**Comment by fionafyzeng** [comment]
@danapj Thoughts about how we should get a UXD to create a mockup of Issue #30 with the tooltip? And then we'll see whether we should find an alternate way to express this. It's nice to get a visual representation first and then collaborate from there as well. I'm neutral about the tooltip as of right now.

Thx for clarifying how this isn't related to the Android Beta Launch. I did get it mixed up.

**Comment by danapj** [comment]
@fionafyzeng yeah sounds good! if you have a UXD available, lmk who I can work with :)

**Comment by dchen97** [comment]
@danapj Do we still have anything left here for UXW to do or is it just UXD?

**Comment by danapj** [comment]
UXD now @dchen97 !

**Comment by dchen97** [comment]
Cool I've unassigned you then and assigned to @findimue to identify a designer whenever one is ready! Thanks @danapj!

**Comment by ghost** [comment]
@dchen97 The mocks look good to me as they are.

**Comment by dchen97** [comment]
submitted an issue for development - https://github.com/oppia/oppia/issues/17124
