### ISSUE TITLE
Mocks for Oppia Language Selector (Android)

### ISSUE THREAD

**Issue by rolandbellerud** [oppia/design-team#33]
**Platform**
Oppia Android 

**Describe the request**
Please provide consultative assistance on the mocks that I've created for the new Language Selector feature for the Android Oppia app. The mocks I have provided are primarily to communicate the general aim for this feature. 

**Context for the request**
- This is a new feature for Oppia on Android
- This fits into the onboarding user journey, but is also going to be a feature that is available in the user settings after they've completed the onboarding process.
- Currently there is no reading language selection option on the Oppia Android app. 

**Link to PRD**
(https://docs.google.com/document/d/14HUwpUev9N3_njg_mjxBBvej72NSMUox7W4ofK88P4U/edit#)
**Mocks Link**
(https://docs.google.com/document/d/1BTYUTNcTqeA1VlG2NsHYNeRm4KPKHPe6epcV4luxRlA/edit#)

**Information about deadlines/priorities**
Deadline TBD.

**Comment by danapj** [comment]
hi @fionafyzeng this is the actual issue for the language selector! @MeganPurvis will work on this for UXW. Let us know who's the designer on this project :) thanks!

**Comment by MeganPurvis** [comment]
@rolandbellerud @danapj Request received! I currently don't have access to all of the relevant document links. Should I request that directly or wait to be given permission?

**Comment by rolandbellerud** [comment]
I approved the existing requests - anything else you need access to?

**Comment by ghost** [comment]
@rolandbellerud What do you need next to move forward on this?

**Comment by ghost** [comment]
Email Roland for status/check-in.

**Comment by rolandbellerud** [comment]
The technical team has what they need as far as the mocks, so I think we can close this out.
