### ISSUE TITLE
Mocks for Oppia In-App Surveys (Android)

### ISSUE THREAD

**Issue by partha-basu** [oppia/design-team#35]
**Meeting Notes**
[[Notes]: In-app NPS Survey](https://docs.google.com/document/d/1s7OZpfVfVGK5nn5ciBaMqPlo344zRyND_jTTQLofanI/edit#)

**Platform**
Oppia Android

**Describe the request**
Need help create the final design based-off rough mocks in PRD. Two parts of this request
- UX design in-line with Oppia design language
- Review/tweak/approve language used in the mocks/feature

**Context**
- The Oppia team is in the process of building out its Android app.
- One of the key success measures (product-market fit) for the app is a score similar to Net Promoter Score (NPS).
- This feature will enable the Oppia team to collect & measure NPS

**Links**
[PRD](https://docs.google.com/document/d/18PfmGJuTlm1psQ3Kv6fXpZgoPzw5q4zhiwrEbRipm60/edit#heading=h.liiqbmwmz8j8)
[MOCKs - slide 1-4](https://docs.google.com/presentation/d/1j-dHs7nCDv4sjUyhhJyjEADfJhLs7O4OJ1LpQCCtA6g/edit?resourcekey=0-sV8NaqEYYLnvYTOXVHIpWA#slide=id.g153361203cf_0_159)

**Deadlines**
TBD

**Comment by fionafyzeng** [comment]
Hi Partha!

Just reaching out to let you know that we see this request.
@Dana P ***@***.***> will assign a UXW and I will assign a UXD for
this request as soon as we can. We'll connect with you once we have the UX
and content designers for you.

Cheers,
Fiona Zeng
UI/UX PROJECT MANAGER AT OPPIA

**Comment by fionafyzeng** [comment]
@danapj posted this request on #uxwriting on Discord on Sep 16, 2022 and had encouraged @MeganPurvis to consider Issue #35. Megan has not responded.

@findimue New UXD Michelle Kang requires a project to work on. I'd love it if you can assess whether she'd be a good fit for this project by introducing Issue #35; Or, feel free to take up this Oppia UXD project yourself to add to your portfolio. Keep me posted :)

**Comment by danapj** [comment]
hi! as Partha has changed the title, we're now aware that this issue is for the in-app survey. @rebekahnt30 is considering working on this for the UXW team. Thanks! @fionafyzeng

**Comment by partha-basu** [comment]
@rebekahnt30 - Just checking if you need any help/clarification on this. Let me know. Thanks!

**Comment by partha-basu** [comment]
@fionafyzeng - Checking in to see if we can prioritize this request please?

**Comment by fionafyzeng** [comment]
Pushing the prioritization now. Will get back to you.

**Comment by fionafyzeng** [comment]
@partha-basu Our newest designer Kaiyu Xu has the capacity to take this on. They do not have a Github account yet, but until then, you can schedule to coordinate through email/Google Chat/video (kaiyu.lilian@gmail.com) or Discord (Kaiyu#6162)

**Comment by rebekahnt30** [comment]
Hi @partha-basu and @fionafyzeng, I've been reviewing the PRD and mocks. I'm located in America eastern time. Let me know when is a good time to meet to discuss.

**Comment by partha-basu** [comment]
I can do my early morning (I'm on the west coast) - Friday? Let me know how we should be connecting - if there is a preference on the mode / contact details.

**Comment by partha-basu** [comment]
Thank you @rebekahnt30 @kaiyuxu @danapj for the kick-off meeting. I'll append the Meeting notes to the original comment/issue at the top for reference & ongoing discussions. We should also update this thread with milestone progress.

**Comment by seanlip** [comment]
Hi @kaiyuxu @rebekahnt30, could you please give an update on the progress of the design/writing for this project? Thanks.

**Comment by partha-basu** [comment]
@seanlip - this is completed. Thanks to @kaiyuxu and @rebekahnt30 - marking it as closed
