### ISSUE TITLE
Transfer AdobeXD Android Design Guide to Figma and finalize Android Design Guide

### ISSUE THREAD

**Issue by ghost** [oppia/design-team#36]
Transfer AdobeXD Android Design Guide to Figma

**Comment by ghost** [comment]
Chantel is working on this and Yan will help.

**Comment by ghost** [comment]
https://www.figma.com/file/y6KqCZAj96JAPzX8nPXKez/Oppia-Android-App-(v01)?node-id=15%3A751
Link to mocks that are a work in progress

Tasks being kept track of on Trello: https://trello.com/invite/b/N4RU8DFU/f62ec218f0405e344f350a3dfc86027b/oppia-android-mocks-adobe-xd-figma

**Comment by ghost** [comment]
@mschanteltc Do you have an idea of what percentage of this still needs to be ported over to Figma?

**Comment by mkanghj** [comment]
All remaining comments are resolved. 
I'm planning to make a video instructions about the Android style guide so that new and current designers can refer back to it when using these design components.

**Comment by seanlip** [comment]
That's amazing -- thank you very much, @mkanghj! Feel free to link the video here once it's done :)

**Comment by mkanghj** [comment]
https://www.loom.com/share/93a66dfe1df5446f81bf6ba0ab12e784

**Comment by seanlip** [comment]
Thanks a lot, @mkanghj! I've updated the video to the [README](https://github.com/oppia/design-team/blob/develop/.github/README.md), and I think we can close this issue!  

/cc @kaiyuxu @yanxxxxxu Just wanted to let you know about Michelle's video in case it's of interest -- see https://www.loom.com/share/93a66dfe1df5446f81bf6ba0ab12e784
