### ISSUE TITLE
Donation Page

### ISSUE THREAD

**Issue by fionafyzeng** [oppia/design-team#37]
**PLATFORM**
Oppia Web

**THE REQUEST**
Update UI. Optimize UX. Revamp the whole page.

**CONTEXT**
Current [donation page](https://www.oppia.org/donate) is out of date.

**DEADLINES**
_TIME-SENSITIVE, URGENT_

- [ ] First iteration: Sep 26, 2022 at 7pm
- [ ] Final iteration: October
- [ ] Launch: November

**Comment by dchen97** [comment]
Marking as Handed off to PM as this is already being implemented (and almost done!)

**Comment by seanlip** [comment]
There is no more design work needed for this iteration, so I'm closing this issue.
