### ISSUE TITLE
Learner Group - Learner Side

### ISSUE THREAD

**Issue by ghost** [oppia/design-team#38]
GSoC PRD [(https://docs.google.com/document/d/11bPIKXHyyeI2WTF4Ujk_4TjPw65TVv-7SAlD8mJZ65U/edit)]

PRD [https://docs.google.com/document/d/1GMkU_Vxi7Y69ZI4gRfxLaDpX-sWfaMZsGQdXasdeELQ/edit]

Figma file [https://www.figma.com/file/t21B6Jx1CuFvZYqVSEvBf2/Learner-Group-(Updated-Mocks-In-Progress)?node-id=0%3A1]

**Comment by ghost** [comment]
Working on UI for Learner Groups Individual Group Pages (aka group home, but called overview to avoid negative connotation of the term group home). Commitment is to have this design done by Thursday night U.S., Friday a.m. IND.

**Comment by danapj** [comment]
@moehaymark will work on the UXW review

**Comment by seanlip** [comment]
I think this is implemented already, closing as it's an old issue.
