### ISSUE TITLE
Android Design System Issues

### ISSUE THREAD

**Issue by juliafalarini** [oppia/design-team#39]
**Platform**
Oppia Android 

**Describe the request**

Design System Issues

**General**

- As a Designer I need general guidance on screen dimension standards (grids, spacing, margin, columns, gutter) to use. This is important to standardize spaces between components. Below I have indicated what I am currently using, but it would be interesting to standardize this.

Grids - I'm currently using 8x8 px
Spacing - I'm currently using of 8/4
Margin - I'm using 28px
Columns - I'm using 8 columns
Gutter - I'm using 8px

- As a designer, I need to know what are the deliverables Design-to-development handoff. Is it necessary to design the screen in more than one dimension or just Android Small? If so, we should standardize the frame sizes that need to be developed.

- As a designer, I need to understand text hierarchy, button, header, body text dimensions, et - I'm currently using text style from [Google Material Design](https://m2.material.io/design) (Roboto) but I think we should also add "Capriola" (Oppia's logo font) to the text style as a Header, since it's a more "fun" font. 

- I would like to have a color style guide, I'm currently using the one from web design system, but I'm not sure of what are "rules" for using this on android.

**Components**

I need to know what are the standards for components regarding edge radius - my suggestion is 8 or multiples.

These are the components that I need to develop for the Onboarding flow, and I'm already working on it. If you agree, we can add them to the Design System later.

- Add/Edit picture/avatar
- Add another profile button
- Language dropdown 
- Text field/PIN field - the current one looks small to me when compared to Google Material Design
- Select profile (teacher/learner)
- Welcome to admin control page

**Icons**

As a designer, I need to know what are the standards to create a new icon, like keyline shapes, for example:

<img width="143" alt="Captura de Tela 2022-10-18 às 21 44 13" src="https://user-images.githubusercontent.com/92189102/196571195-cf9f6c0a-e2de-465d-ac63-42621e579bcc.png">

(This example has a 24x24px frame, 20x20px keylines, 2px stroke)

- What are our keyline shapes sizes?
- What is our icon frame size?
- What is our icon stroke size?
- What are the margins between the keyline shapes and frame?
- Should we have icons 24x24px and 20x20px?

These are the icons I need for the Onboarding flow (for now), and I'm already working on them, following the standards from the example icon indicated above.

- Check
- Pencil/edit - done
- Options
- Help
- Add new profile
- Administrator controls
- Profile Management
- Settings
- Account actions

**Context for the request**

I'm working on the Onboarding user flow, and I need some standards from the Design System in order to develop a consistent UI. 

**Link to Figma File**
This is the link to the [Onboarding Figma File](https://www.figma.com/file/PnCtQKDR5VWbIlA3Ui7rTa/Oppia---Onboarding-Android-App?node-id=1011%3A3370).

**Information about deadlines/priorities**
I'm first working on a mid-fidelity prototype to start testing with users. In the next two weeks I will be conducting tests, and possibly new questions and issues may arise after that. My deadline for submitting this project to development is December 20th, so it would be important to have a consistent Design system as soon as possible - November 20th if possible.

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [ ] UX Design approved (tag @findimue or @fionafyzeng once ready for UXD review) 

- [ ] UX Writing approved (tag @danapj once ready for UXW review) 

- [ ] Product approved (tag @dchen97 (for web projects) or @seanlip (for Android projects) once ready for product review)

**Design project is not complete until all of the above approvals are complete**

**Comment by ghost** [comment]
"As a designer, I need to know what are the deliverables Design-to-development handoff. Is it necessary to design the screen in more than one dimension or just Android Small? If so, we should standardize the frame sizes that need to be developed."
We need the screens 720 width by 1080 height for tablet as well as the mobile for Android.

**Comment by ghost** [comment]
Regarding icons, we would use Material Design icons whenever possible. Custom icons would follow the parameters laid out for Material Design: https://m2.material.io/design/iconography/system-icons.html#design-principles

**Comment by ghost** [comment]
I created a simple grid and shared the link, but pasting here for redundancy. 
https://www.figma.com/file/6uVMg4wf731DmCYFVTNAaj/Oppia-Material-Design-Grid?node-id=0%3A1
https://m2.material.io/components/app-bars-top#specs
https://m2.material.io/components/app-bars-bottom#specs

**Comment by mschanteltc** [comment]
Hi Julia, thanks for this breakdown! Just wondering, how important is it to have components animate from one state to another? For example, the dropdown menu is one of the most difficult components to create since it transitions from a collapsed to an expanded state, and vice versa. 

Also you can use this as a [reference](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/grid) for layouts in different viewport.

**Comment by juliafalarini** [comment]
> Regarding icons, we would use Material Design icons whenever possible. Custom icons would follow the parameters laid out for Material Design: https://m2.material.io/design/iconography/system-icons.html#design-principles

Thanks @findimue, looks good!

**Comment by juliafalarini** [comment]
> I created a simple grid and shared the link, but pasting here for redundancy. https://www.figma.com/file/6uVMg4wf731DmCYFVTNAaj/Oppia-Material-Design-Grid?node-id=0%3A1 https://m2.material.io/components/app-bars-top#specs https://m2.material.io/components/app-bars-bottom#specs

@findimue thanks! do we also have the parameters for margins, columns and gutters?
and can I have this same file for tablet 720x1080?

**Comment by juliafalarini** [comment]
> Hi Julia, thanks for this breakdown! Just wondering, how important is it to have components animate from one state to another? For example, the dropdown menu is one of the most difficult components to create since it transitions from a collapsed to an expanded state, and vice versa.
> 
> Also you can use this as a [reference](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/grid) for layouts in different viewport.

Hi @mschanteltc thanks for sharing! About the dropdown, I created on based on the Material Design, you can check it [here](https://www.figma.com/file/PnCtQKDR5VWbIlA3Ui7rTa/Oppia---Onboarding-Android-App?node-id=1035%3A4122). Do you think we can integrate it to the Design System?

**Comment by seanlip** [comment]
Hi @mkanghj -- assigning this to you since you're working on the Android design style guide :) Just to check, is everything in this conversation thread resolved/included, or are there bits left to do? (Wondering if we can close this issue yet.)

Thanks!

**Comment by mkanghj** [comment]
Hi @juliafalarini Android design system includes the screen dimension standards and icon components to use. You can choose the relevant icons for onboarding and modify the side bar item component. Please reach out to me directly if you have any questions or requests to change about the current android design system. @seanlip Everything is resolved

**Comment by seanlip** [comment]
OK, thanks a lot @mkanghj ! Closing this issue then.
