### ISSUE TITLE
Web Design Style Guide - Missing/Wishlist Items

### ISSUE THREAD

**Issue by ghost** [oppia/design-team#40]
Wishlist for Design style guide

https://www.figma.com/file/nrQrOxSxSg1oabuVE6XJpa/Oppia-Design-Guide?node-id=312%3A2506&t=P8vILcnWt7Ena5FR-1

Figma designs of current

- [x] Web header

- [x] Web footer

- [x] Tooltips

**Comment by dchen97** [comment]
Could we also add one item for tooltips?

**Comment by ghost** [comment]
@dchen97 Sure. Do you have examples of tooltips you want them modeled after, or do you want a new tooltip template created for future use?

Unify tooltips. Reference existing samples.

**Comment by seanlip** [comment]
This is all basically done -- thanks @kaiyuxu! Final doc is here: https://www.figma.com/file/nrQrOxSxSg1oabuVE6XJpa/Oppia-Design-Guide?node-id=312%3A2506&t=7Cuf55TXw0qNNIz4-0

Remaining things to do:
- [x] Check with @mschanteltc about the two stray colours in the colour palette -- and figure out whether these are meant to replace any of the existing colours on the main palette (even though they're currently not used on the website).
- [x] File an issue on https://github.com/oppia/oppia/issues requesting colour changes to the hover state (and giving some examples of what needs changing), and any other colour changes needed generally after the discussion with @mschanteltc.
- [x] Make sure that this is well-integrated into the "new design contributor onboarding process" and that every Web designer on Oppia knows about it and is actively using it as a reference (and isn't blocked from doing so in any way) -- talk to @findimue + @jennyjae about this too.

**Comment by ghost** [comment]
@seanlip I've updated the language around the web and Android design style guides in the Onboarding Deck and reminded designers of its existence/requested its use in Discord.

**Comment by seanlip** [comment]
Thanks @findimue! @kaiyuxu has also filed the issue https://github.com/oppia/oppia/issues/17251 and we've had the discussion with Chantel, so I think we can close this issue.

Thanks everyone!
