### ISSUE TITLE
Doubts and Suggestions - Android Design System

### ISSUE THREAD

**Issue by juliafalarini** [oppia/design-team#41]
I've been working on the prototype for the Android Onboarding Flow, and we finished the first round of testing. Now I'm working to fix some issues and adjust the prototype to a high-fidelity according to the Design System, and I have some questions and suggestions.

**Platform**
Oppia Android

**Describe the request**

**Typography**

- Is the Line height always "Auto" for all text styles? 
- Can I use black #00000 as the color for the text? (we don't have this color on the design system)
- I would like to add Capriola as a font for the Design System 20(size)/24(height) 

**Margins**
According to the grid, the margins should be 24px or 32 px, my suggestion is 24px - is that okay?

**Colors**

- The color is #264653 is part of the sidebar but it's not on the design system.
- Add the color #BDDAEF to the design system. This color is on the background of the Classroom web, and I would like to use it on Android: <img width="281" alt="Captura de Tela 2022-11-30 às 14 47 40" src="https://user-images.githubusercontent.com/92189102/204870732-5b0a292f-a9bd-4957-8243-d4d7d3b26d86.png">
- Add the color #BEE9DF

**Components**

- Language selector - I'm using the language selector from the material design, is that okay? 
- The components from the Design System aren't following text style from Figma.

About the menu Sidebar:
- The margin is 18px, if we agree that the margin is 24px, should we adjust it to 24px?
- I edited the side bar menu because of the results of the tests (switch profile action closer to the top) - after the final tests, this might need to be updated in the design system.
- The text of "topics in progress and stories completed should be divided into two rows, since the text won't fit in one row in other languages.
- I think we can add a "pencil" button for them to edit their profile, since it's not so obvious that they can click on the photo to edit it. – let them edit if they click on the photo and if they click on the pencil.

- I created a new component to select the profile, if you agree we can incorporate it to the Design System.
- I created a new component to add a profile picture, if you agree we can incorporate it to the Design System.

**Context for the request**
I'm working on the Onboarding Flow and testing it with users, so I need to align my design with the Design System as soon as possible.

**Link to Figma File**
[Figma File
](https://www.figma.com/file/PnCtQKDR5VWbIlA3Ui7rTa/Oppia---Onboarding-Android-App?node-id=1446%3A11977)

**Information about deadlines/priorities**
This time-sensitive, since I should start the last round of tests by December 6.

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [ ] UX Design approved (tag @findimue or @jennyjae once ready for UXD review) 

- [ ] UX Writing approved (tag @danapj once ready for UXW review) 

- [ ] Product approved (tag @dchen97 (for web projects) or @seanlip (for Android projects) once ready for product review)

**Design project is not complete until all of the above approvals are complete**

**Comment by juliafalarini** [comment]
<!--
I've been working on the prototype for the Android Onboarding Flow, and we finished the first round of testing. Now I'm working to fix some issues and adjust the prototype to a high-fidelity according to the Design System, and I have some questions and suggestions.

**Platform**
Oppia Android

**Describe the request**

**Typography**

- Is the Line height always "Auto" for all text styles? 
- Can I use black #00000 as the color for the text? (we don't have this color on the design system)
- I would like to add Capriola as a font for the Design System 20(size)/24(height) 

**Margins**
According to the grid, the margins should be 24px or 32 px, my suggestion is 24px - is that okay?

**Colors**

- The color is #264653 is part of the sidebar but it's not on the design system.
- Add the color #BDDAEF to the design system. This color is on the background of the Classroom web, and I would like to use it on Android: <img width="281" alt="Captura de Tela 2022-11-30 às 14 47 40" src="https://user-images.githubusercontent.com/92189102/204870732-5b0a292f-a9bd-4957-8243-d4d7d3b26d86.png">
- Add the color #BEE9DF

**Components**

- Language selector - I'm using the language selector from the material design, is that okay? 
- The components from the Design System are following text style from Figma.

About the menu Sidebar:
- The margin is 18px, if we agree that the margin is 24px, should we adjust it to 24px?
- I edited the side bar menu because of the results of the tests (switch profile action closer to the top) - after the final tests, this might need to be updated in the design system.
- The text of "topics in progress and stories completed should be divided into two rows, since the text won't fit in one row in other languages.
- I think we can add a "pencil" button for them to edit their profile, since it's not so obvious that they can click on the photo to edit it. – let them edit if they click on the photo and if they click on the pencil.

- I created a new component to select the profile, if you agree we can incorporate it to the Design System.
- I created a new component to add a profile picture, if you agree we can incorporate it to the Design System.

**Context for the request**
I'm working on the Onboarding Flow and testing it with users, so I need to align my design with the Design System as soon as possible.

**Link to Figma File**
[Figma File
](https://www.figma.com/file/PnCtQKDR5VWbIlA3Ui7rTa/Oppia---Onboarding-Android-App?node-id=1446%3A11977)

**Information about deadlines/priorities**
This time-sensitive, since I should start the last round of tests by December 6.

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [ ] UX Design approved (tag @findimue or @jennyjae once ready for UXD review) 

- [ ] UX Writing approved (tag @danapj once ready for UXW review) 

- [ ] Product approved (tag @dchen97 (for web projects) or @seanlip (for Android projects) once ready for product review)

**Design project is not complete until all of the above approvals are complete**

**Comment by juliafalarini** [comment]
test

**Comment by seanlip** [comment]
@mkanghj Could you please confirm whether all the things listed here have been done/addressed? If so, we can close this issue.

Thanks!

**Comment by mkanghj** [comment]
@juliafalarini Sorry for delayed reply! I haven't checked this github for a while. Please reach out to me directly if you have more questions. Below are my comments based on your questions. 

Typography 
- Line height is always "Auto" for all text styles, but it it looks packed or far from each other, please use equation (Font size * 1.3)
- According to the android design system, we use charcoal rather than black for text 
- do you need the Capriola as a header only?

Margins - 24px is correct

Colors - I can added 3 colors that you've requested

Components -we have language selectors for language dialog box component 

Sidebar component - do you mean to add "close" button for sidebar? I can incorporated what you've created the sidebar from your figma.

**Comment by mkanghj** [comment]
just want to make sure that we use #205D86 for the sidebar color, not #264653

**Comment by mkanghj** [comment]
Requested colors, updated sidebar component, and Capriola typography info are added. @seanlip resolved all of comments. @juliafalarini Please reach out to me if you have any questions. Thanks!

**Comment by seanlip** [comment]
Thank you so much, @mkanghj! Closing this issue since it's done, but @juliafalarini please feel free to reopen it if anything additional is needed. Thanks!
