### ISSUE TITLE
Contributor Dashboard onboarding flow

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#42]
**Platform**
Oppia Web

**Describe the request**

When a new contributor visits the contributor dashboard (CD) page at Oppia.org, there is no onboarding provided. The aim of this project is to:

- Design the "you are logged out, please log in" experience for the CD
- Direct logged-in users to a Google Form if they are not accepted as a translator/question contributor yet
- Provide guidance on what the CD is for and how to use it
- Ensure that, after a contributor is given rights to submit translations/questions, that their user experience "flows" well (e.g. they get an email, that email directs them to the dashboard, and they can start with their first translation and do something successful -- this may require coordination with whoever is working on the submission UI).

This ticket/issue concentrates on:

>
> Design the "you are logged out, please log in" experience for the CD
>

**Context for the request**

This feature doesn't really exist currently -- logged-out users just get asked to log in, and for logged-in users:
- They can translate anything immediately (this shouldn't be the case; they should be directed to a signup form and, in general, only given access to languages that they have been granted permissions to translate in)
- They can't see the question submissions tab at all, so they don't know that it exists.

**Link to PRD**

There is no PRD for this yet, but I've talked to @jennyjae and she thinks that the design team should be able to make a start with the above information.

**Information about deadlines/priorities**

We expect the tech team to start writing design docs for this in mid-Feb because we expect to offer this as a coding project for the summer. /cc @dchen97 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by jennyjae** [comment]
Priority Focus:
1. #42 CD Onboarding Flow
2. #43 CD Submission Workflow
3. #9 CD Reviewer Dashboard
4. #7 CD Contributor Recognition

Met with Jonathan 12/21.

Next Milestone: Design Mocks for Onboarding landing page (Providing guidance on what the CD is for and how to use it + Log-in feature)

Due: January 9th, 2023

**Comment by seanlip** [comment]
This ha been split into #112, #113, #114, #115 and #119, so I'm closing it.
