### ISSUE TITLE
Contributor Dashboard Submission Workflow

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#43]
**Platform**
Oppia Web 

**Describe the request**
The aim of this request is to create mocks for submitting translations and practice questions to the contributor dashboard. We would also like there to be some element of recognition when the contributor achieves a milestone (e.g. submits their first translation), as well as an onboarding pathway to help them get started with their first contributions.

**Context for the request**
This is an existing feature. There is a PRD [here](https://docs.google.com/document/d/1gzA9jJVlPt-DHxXwZXOQaoeN2mjFo8Qni0In193ypLI/edit) that is in progress, please contact @dchen97 for any details that need to be finalized.

This is one of the core journeys for the contributor dashboard, since it is how translation and practice question submitters contribute translations and practice questions into the system for reviewers to review. You can play through the current experience at our test server: oppiatestserver.org/contributor-dashboard.

You might also be interested in issues faced by translation submitters and question submitters currently. These are chronicled here: https://github.com/orgs/oppia/projects/18/views/7?filterQuery=-status%3ADone+specific-audience%3A%22Translation+submitters%22%2C%22question+submitters%22+. Note that some of these are just technical bugs, but some of them may also relate to the user experience.

**Link to PRD**
https://docs.google.com/document/d/1gzA9jJVlPt-DHxXwZXOQaoeN2mjFo8Qni0In193ypLI/edit

**Information about deadlines/priorities**

The mid-fi design needs to be done by Feb 15 so that we can offer this as a coding project to the technical team for a program that opens applications in late Feb.

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [ ] UX Design approved (tag @findimue or @jennyjae once ready for UXD review) 

- [ ] UX Writing approved (tag @danapj once ready for UXW review) 

- [ ] Product approved (tag @dchen97 (for web projects) or @seanlip (for Android projects) once ready for product review)

**Design project is not complete until all of the above approvals are complete**

**Comment by jennyjae** [comment]
Priority Focus:
1. #42 CD Onboarding Flow
2. #43 CD Submission Workflow
3. #9 CD Reviewer Dashboard
4. #7 CD Contributor Recognition

Met with Jonathan 12/21.

Next Milestone: Design Mocks for Translation & Practice Question Submissions

Due: January 16th, 2023

**Comment by IMHieuVo** [comment]
Per March 06, 2023, Contributor Dashboard meeting, Sean advised breaking the design portion into smaller parts.

**Comment by seanlip** [comment]
Closing this in favour of #65, #66, #67 and #68.
