### ISSUE TITLE
Concept Card Translation (coupled with #56)

### ISSUE THREAD

**Issue by ghost** [oppia/design-team#44]
[PRD](https://docs.google.com/document/d/1ADDaL2yFLcyewsgZ4dkp770mfsvQoQizyHaze6re6zo/edit)
At a high level - Concept cards cannot be translated at all today which means there's some content that can appear in our lessons that are completely inaccessible to learners! This project entails adding changes to the learner and Contributor Dashboard experiences to enable translation (and even auto-translation) of concept card content so we can fill this urgent gap.

**Comment by danapj** [comment]
@Tiafreels will be the UXW on this. Can I check is there a UXD assigned to link up with as well?

**Comment by seanlip** [comment]
Yup, @IMHieuVo will be taking this on from the UXD side.

**Comment by seanlip** [comment]
(Note that this is also coupled to #56 -- revision cards are also currently not represented on the contributor dashboard.)

**Comment by dchen97** [comment]
Issue filed - https://github.com/oppia/oppia/issues/17650

**Comment by seanlip** [comment]
Link to mocks: 
https://www.figma.com/file/f1LKmZEbJv3E0CKYNHgAzY/HV-Oppia-Design-File?node-id=70%3A795&t=DKqwEgGfOauZYcxX-1
