### ISSUE TITLE
Streamline and Modernize Contact Us page

### ISSUE THREAD

**Issue by ghost** [oppia/design-team#47]
This is an upcoming PRD that is very close to being finished that will need UX design and writing assistance. This project involves updating one of our static pages - the Contact us page - to be more streamlined and modern looking.

[PRD](https://docs.google.com/document/d/1hN4Fii8taHu_GW3yifzjNeGzK7oVQFwTibga22-gLWk/edit?pli=1#)
[PM Mocks](https://docs.google.com/presentation/d/1GEPXV1obZ9RSm4ZJohdAgKwSXPLTJZHTYX5qDVq-IwE/edit) (meant to help give direction, not meant to be final designs or mocks)
PM Contact: [@Yupin Ang](mailto:yupin93@gmail.com)

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by ghost** [comment]
@Ronnie-Mercy Would you be able to take on this project instead, Ronnie? I don't want you to be stuck waiting for answers any longer than you have been. Please check out the PRD and the current mocks that are linked above, and let me know what you think.

**Comment by ritz-bitz** [comment]
Link to the Contact Us Page assets : [Contact Us Page Assets ](https://drive.google.com/drive/folders/1WjBUyfT_d33l42V8uUrQIAk81uCtYpTO?usp=sharing)

**Comment by seanlip** [comment]
@jikim322 @roxanashirazi Could one of you please sign off on this for UXW (see the checkbox at the top)? Thanks.

**Comment by jikim322** [comment]
UXW review of the page is complete -- I did leave one comment about button text casing for the developer because I didn't want to mess with the style component on Figma. Most of our the website uses all caps so have asked that buttons on this page also be all caps.

**Comment by seanlip** [comment]
Thanks @jikim322!

@jikim322 @roxanashirazi @ritz-bitz @ConorMack @rfinch11 Can we wrap up the handoff for this please? It should have UXD/UXW approval (in the top comment) once everything is good to go. Thanks!

**Comment by yupigummy** [comment]
Can't seem to mark the "Product approved" checkbox as complete in the original post. Please take this as my sign-off on the Contact Us page. Next step: will raise an issue/request to the dev team. 

- [x] Product approved

**Comment by seanlip** [comment]
Closing since this issue is complete from the design side.
