### ISSUE TITLE
Canonical way to end practice session

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#48]
See [Issue #14209](https://github.com/oppia/oppia/issues/14209)

PM: Diana

Platform: Web

Request: Would like a way for a user to canonically exit a practice session early if they'd like to. When the user tries to do this, they should see a dialog that asks them to confirm and then will lead them to the practice session results page which will successfully show them the results of the session for the questions they did answer. 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by juliafalarini** [comment]
This was handled in the project #97

**Comment by seanlip** [comment]
Thanks, closing as a duplicate.
