### ISSUE TITLE
Language Management and Auto-translations for Lessons

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#49]
Platform: Web

Requires UXD and UXW 

PM: @dchen97 

[PRD](https://docs.google.com/document/d/1TeGQQNLNJWkTgvGQ1xmV6snz8zXnJ23TvuDKtK5_Tok/edit#)

Figma: https://www.figma.com/file/bDpYCIrETMBvFoSmEHdFLn/%2349-Design-Document?type=design&node-id=91%3A78&t=G8FKDIBxtZ7YyXfW-1

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by seanlip** [comment]
@IMHieuVo Is there a reason you marked this as "handed off to PM"? None of the UX lead approval boxes have been checked...

**Comment by IMHieuVo** [comment]
@seanlip Sorry, I did change the Project Board since Kate and I were satisfied with the mocks. And on that note, is it that okay to have Kate approve the UXW portion or does this need to go to Dana?

**Comment by danapj** [comment]
I'm okay for Kate to approve it since she's most familiar with the CD
projects :)

**Comment by kmuir1991** [comment]
Hi all. Is this all good? I was going to check the UXW box, but I see it's already been checked...

**Comment by jc9536** [comment]
Hello everyone,

I believe I mentioned this in one of our weekly meetings, but all UXW and
additional comments/note changes have been made to the handoff, so
everything should be all set/ready for handoff. I do not believe I missed
anything as per Sean and Kate's comments. If I did, please let me know.
Have a great weekend everyone!

Thanks,
Jaimie Chin

**Comment by seanlip** [comment]
@jc9536 -- Sorry for the late reply on this. Left a couple of comments -- please address and reassign to me once you're done with them, then I can file it. Thanks!

(Please also update the status of this issue to "Handed off to PM" once done. Thanks!)

**Comment by seanlip** [comment]
Filed on https://github.com/oppia/oppia/issues/18766. I noticed that this covers points 1+2 of the PRD solution summary but not point 3 (which also needs some design work). However, that part is more on the LaCE side so I'll file a new issue for it.

Thanks @jc9536 for working on this!
