### ISSUE TITLE
Setting context for reviewers and contributors for translations 

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#52]
**Platform**
Oppia Web

**Describe the request**
Provide a way for contributors (namely translators) and reviewers to see the context in which the item being translated is presented in a lesson.

[PRD](https://docs.google.com/document/d/1lIXkcQwPcPeS715vhX6mY-lowzltLxE8v2QQEvFadks/edit?pli=1)

Figma: https://www.figma.com/file/EWrumZEJ1vQpe9odmNaxun/Oppia-Contributor-Dashboard%2FReview-Translations?node-id=121%3A81&t=Wx3BNhOnjAEn9cCe-1

PM for project: @dchen97 

**Context for the request**
New feature to be added to the Contributor Dashboard

Helps to inform reviewers and translators who are trying to translate our lessons but currently have no way of knowing where the translation will actually appear. 

**Link to PRD**
[PRD](https://docs.google.com/document/d/1lIXkcQwPcPeS715vhX6mY-lowzltLxE8v2QQEvFadks/edit?pli=1)

**Information about deadlines/priorities**
Not time sensitive but would be nice to streamline the reviewing and translating processes. 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by seanlip** [comment]
@DeeMoh21 I left one comment on your mock. Could you please take a look? Thanks.

(Please set the status to "Handed off to PM" once done.)

**Comment by DeeMoh21** [comment]
@Sean Lip ***@***.***> , I took care of it, thank you!
Thanks and Best Wishes
Deepika Mohanty

**Comment by seanlip** [comment]
Thanks @DeeMoh21!

**Comment by seanlip** [comment]
Filed this as part of https://github.com/oppia/oppia/issues/18511, and marking this issue as closed/completed from the design side. Thanks @DeeMoh21!
