### ISSUE TITLE
For translation reviewers, auto-display alt-text for images

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#54]
**Platform**
Oppia Web

**Describe the request**
Streamline the reviewer process for the Contributor Dashboard by auto-displaying alt-text for images that have been translated and need review

**Context for the request**

This is a new feature for the Contributor Dashboard to streamline the review process. 

Alt-text is required for all of our images and thus must be translated. However, we currently require reviewers to go through an extra click to see the alt-text for an image, which is not very useful or efficient.

**Link to PRD**
[PRD](https://docs.google.com/document/d/1lIXkcQwPcPeS715vhX6mY-lowzltLxE8v2QQEvFadks/edit#heading=h.liiqbmwmz8j8)

**Information about deadlines/priorities**
Not time sensitive but will be helpful for streamlining our translation review processes.

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [ ] UX Design approved (tag @jennyjae once ready for UXD review) 

- [ ] UX Writing approved (tag @danapj once ready for UXW review) 

- [ ] Product approved (tag @dchen97 (for web projects) or @seanlip (for Android projects) once ready for product review)

**Design project is not complete until all of the above approvals are complete**

**Comment by seanlip** [comment]
Update: I made this issue more specific to just the alt-text part since we decided to scope out the resubmission side of things.

**Comment by sagangwee** [comment]
Noting that these mocks will be need for the GSoC project https://github.com/oppia/oppia/wiki/Google-Summer-of-Code-2023#23-improvements-for-translation-reviewer-experience (wiki link being updated).

**Comment by dchen97** [comment]
Issue filed - https://github.com/oppia/oppia/issues/17648
