### ISSUE TITLE
Android App Feedback feature

### ISSUE THREAD

**Issue by rolandbellerud** [oppia/design-team#57]
**Platform**
Oppia Android

**Describe the request**
Review of the mocks that have been created for the Android app feedback submission feature. The goal is to consult the design team on whether there are any UX updates that should be made to the mocks (the way things are arranged, text, color, etc.). We are looking for a review of the overall UX, rather than formatting such as spacing, text fonts, etc. 

**Context for the request**
Please provide enough context for the request. For example:
- Is this a new or existing feature?
This is a new feature. 
- What is the broader user journey that this feature fits into?
This fits into the journey of users who want to share their experience in the app with us, or let us know when something is broken or wrong.
- What is the current user experience like (where is the user located before they encounter this feature)? 
This feature does not yet exist in the app, so there is no current experience. 

**Link to PRD**
https://docs.google.com/document/d/1ssV3eh0RtAR7YlatxdQoLG2KOJ-Qri33trYJr0AIw-o/edit#

Mocks: https://docs.google.com/document/d/17R8e-2FnDklUsxqUNRmRK2LqJetM_j7lq0I-Mff5SPc/edit#

**Information about deadlines/priorities**
If possible, this should be ready by the GA launch of the Android app.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by kaiyuxu** [comment]
Hi @rolandbellerud , we're interviewing designers and will get back to you as soon as we have resources

**Comment by seanlip** [comment]
Hi folks, this has been sitting for a while. Can we get UXW and UXD approval, or is there more to do here?

/cc @jiwonc26 @kaiyuxu @jlevick @kmuir1991

**Comment by jlevick** [comment]
@seanlip I'm not sure if the final designs are finished, as there were comments on what was labeled "final". If no other changes are to be made @jiwonc26, then I am happy to sign off on this for UXW.

**Comment by jiwonc26** [comment]
The design itself is completed (so no more UXW assistance is needed!) but I
would need to do more work regarding the dark mode. The dev team told me
that they haven't set the colors for the dark mode and the design team
should decide on which colors to use. I am still working on which color
palette I should use..

Sean, would you want me to just sign off the project as-is, and work on the
dark mode stuff later? The light mode prototype is final & confirmed by the
dev team.

2023년 9월 14일 (목) 오전 6:17, Jaime Levick-Oxner ***@***.***>님이
작성:

**Comment by jlevick** [comment]
Thanks for the clarification, @jiwonc26! I've approved this for UXW.

**Comment by jiwonc26** [comment]
+ Actually I'd need to modify a few things on my prototypes, but they will
be quick changes. I can just fix them today

**Comment by seanlip** [comment]
Thanks @jiwonc26! Hm, I'd say let's wait till dark mode is completed before wrapping this up -- thanks for checking!

**Comment by seanlip** [comment]
Just putting the link to mocks in this issue directly for easy reference: https://www.figma.com/file/d2zD9RGnIbnX8q0uOKYNVD/Final---App-feedback?type=design&node-id=0%3A1&mode=design&t=aVm0CDccpkfD1yJn-1

**Comment by seanlip** [comment]
This has been filed as https://github.com/oppia/oppia-android/issues/5333. Closing as completed. Thanks @jiwonc26 and @jlevick for your work on this!
