### ISSUE TITLE
Redesign the lesson player

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#58]
[Figjam](https://www.figma.com/file/r04T6TwgpCqdqXhn9AiOCN/Lesson-Player-IA-Brainstorm?node-id=0%3A1&t=IjXNJvjnx2O91wzz-0)

[Mini-PRD](https://docs.google.com/document/u/1/d/1922aE9_TEFTbHyA3jrXy9cTxo2JgvjfEvKHlxqxG-Rw/edit)

[Mock brainstorm](https://www.figma.com/file/d4CXFAaBmw0hPnYS90A9CO/Oppia_Player-redisign?t=e8B27Nc7kzbcb17n-0)

PM: @dchen97 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by juliafalarini** [comment]
**Done**

- Wireframes/Lo-fi prototype for Lesson player (has been reviewed by Diana (PM) and Rebekah (UXW)).
- [Research Plan](https://docs.google.com/document/d/1ixee6_9Dsf89Hob5N3cBI25YY7iw7ORxS-HLGKVgExU/edit?usp=sharing) 

**In progress**

- Conducting usability tests with users


**Next steps (by March 22nd):**

- Consolidate results from tests and finish necessary adjustments in the low-fi flows/wireframes; 
- Update the research plan so more feedback can come in

**Comment by juliafalarini** [comment]
[Submitted Reports for Web Improvements Research - Spreadsheet](https://docs.google.com/spreadsheets/d/1BNkynOkA4H_uEIFwf9-6qFJYhcxfFU8cfuXZgI3UetQ/edit?usp=sharing)

**Comment by juliafalarini** [comment]
Consolidating the tests results [here](https://docs.google.com/spreadsheets/d/18Hyoy2yWgAsgAKVCt1lTVd8DajGu1vM4YIAdqme_tLQ/edit?usp=sharing). @dchen97 has reviewed it. Waiting for @sarahking22 to find a time to meet and discuss it.

**Comment by juliafalarini** [comment]
After consolidating results, I have updated the mocks and created a second version of the [Research Plan](https://docs.google.com/document/d/1l5C-FmPeuzMwH0aBF2pal0lqyqaleBn6WxkLuZ9DOOE/edit?usp=sharing) and [Prototype](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?node-id=3521-27960), to test some improvements. One Outreachy contributor has already submitted a [report](https://docs.google.com/spreadsheets/d/1swIL-orNlcE-R6bqqDyb95vaN2zXZw56Dgzg5TrKaB4/edit?usp=sharing).

**Comment by juliafalarini** [comment]
Working on [hi-fi mocks](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194)!

**Comment by juliafalarini** [comment]
This project is finalized and I'm just waiting for the final approval of all leads. The final design can be found here: https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design

**Comment by rfinch11** [comment]
@roxanashirazi do we have your signoff on this project?

**Comment by ghost** [comment]
Hi Team,

UXW has signed off on this project!

Thank you,

Roxana

**Comment by seanlip** [comment]
This is now filed on the GitHub developers' issue tracker at https://github.com/oppia/oppia/issues/19217.
