### ISSUE TITLE
Consolidated Web User Feedback

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#59]
Platform: Web

PM: @dchen97

Needs UXD and UXW 

[PRD](https://docs.google.com/document/d/1ZUD7nktZrl5ZyxcXfLAqJqb6wI40U9rdg-2vHHWUZ1g/edit#heading=h.liiqbmwmz8j8)

**Comment by dchen97** [comment]
Thanks @ConorMack! Only very minor design notes but overall the flows make sense to me!

**Comment by ConorMack** [comment]
Thanks Diana, I'll read these over tomorrow and make adjustments.

**Comment by dchen97** [comment]
[Filed issue](https://github.com/oppia/product-operations-team/issues/51)
