### ISSUE TITLE
Number line interaction

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#6]
Description: Add an interaction that allows users to answer using a [number line](https://byjus.com/maths/number-lines/).

**Web links:**

- https://docs.google.com/document/d/1cha8e5H4Dfb7t8cLL2VZYi02Ysk2YEdyyalY1dDqPXE/edit#heading=h.rpq25vez37fp
- https://www.figma.com/file/n5hOKwKFxBTx6umyEU8yfB/Numberline-interaction

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by ghost** [comment]
Assigned to Chloe; will resume within a couple weeks

**Comment by ghost** [comment]
Assign to another designer

**Comment by dchen97** [comment]
What's the status of this project?

**Comment by ghost** [comment]
I have it open on my computer to figure that out. It seems like it has some
wireframes/lo-if work done so far.

**Comment by ghost** [comment]
@cwg421 Did you work on the number line interaction previously? Is it something you'd be willing to work on more? Right now, it looks like the last work that was done was only low fidelity. Please let me know!

**Comment by cwg421** [comment]
Yes, I previously worked on this project, and I can continue working on it!
Thanks!

**Comment by danapj** [comment]
I'll provide a UXW review of this shortly

**Comment by danapj** [comment]
@cwg421 moving some prelim UXW comments into your figma file!

**Comment by dchen97** [comment]
Filed [issue](https://github.com/oppia/oppia/issues/18382)
