### ISSUE TITLE
Android App Deprecation notification feature

### ISSUE THREAD

**Issue by rolandbellerud** [oppia/design-team#62]
**Platform**
Oppia Android (delete one)

**Describe the request**
General consultation on ensuring the notification aligns with Oppia's design principles and format. 

**Context for the request**
Please provide enough context for the request. For example:
- This is a new notification that will be used in cases where an old version of the Oppia Android App will be deprecated.
- This fits into the user journey for those who need to be notified and may not necessarily be able to update their app when we offer a new version.

**Link to PRD**
(https://docs.google.com/document/d/1ndlaLALUhNFevdLzVmXyJr4UD3HuhMKpo9VfmB0sY4g/edit#)

**Information about deadlines/priorities**
This feature is not time sensitive, and can be prioritized based on available resources. 

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [x] UX Design approved (tag @kaiyuxu once ready for UXD review) 

- [x] UX Writing approved (tag @danapj once ready for UXW review) 

- [x] Product approved (tag @seanlip once ready for product review)

**Comment by seanlip** [comment]
Initial mocks: https://www.figma.com/file/2dohUd2hHPAvhehWWygw7k/oppia-me?type=design&node-id=1001-3447&t=sD1i4Af9ST2oRl6f-0

Final version: https://www.figma.com/file/dTWHwMDdZ8RUrR3rFmzxey/Oppia-deprecation-project?type=design&node-id=0-1&t=x3eoOfvFXAf4KXPd-0

**Comment by seanlip** [comment]
Approving for Product. @danapj @kaiyuxu could you PTAL and approve/comment as needed for any UXD/UXW issues? (Please use the design approval checklist above.)

Thanks!

**Comment by seanlip** [comment]
Closing since this is filed on https://github.com/oppia/oppia-android/issues/5025. I tagged @danapj @jlevick @jiwonc26 on that issue so they can follow along, too!

Also congrats @jiwonc26 and @jlevick on finishing your first full design projects on Oppia :)
