### ISSUE TITLE
Update Web/Android style guides to incorporate core design principles

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#63]
**Platform**
Oppia Web/Android design guide

**Describe the request**

We have a [general design guide document](https://docs.google.com/document/d/1R9PWRBA7yPCiHxc325gx1xHd_RMLRlCjMFWDCowUPag/edit#heading=h.ngrlf0evgyy) that has just been archived, but on conversation with Chantel (the author), it seems that the "Design Principles" section is not reflected in the current [Figma style guides](https://www.figma.com/file/nrQrOxSxSg1oabuVE6XJpa/Oppia-Design-Guide?node-id=0%3A1).

The aim of this issue is to add a new section in the Figma style guide called "Design Principles" (which would be on the same level as "Typography" and "Components") and mention the corresponding details in the doc in their own artboard. Note that this only applies to the "Design Principles" section in the document, and not the Typography or Color sections. If there are any conflicts between the Design Principles in this doc and the ones in the Figma guide, then a discussion should be held with the design team to figure out what to do.

**Context for the request**

This is an incremental update to the existing Web style guide. It aims to ensure that previously-defined principles are not lost as we move to the new Figma style guides.

**Information about deadlines/priorities**
There is no external deadline, but it would be helpful to tackle this sooner rather than later so that designers can make use of the new information in their designs.

**DESIGN APPROVAL CHECKLIST - DO NOT EDIT THE FOLLOWING --- ONLY REVIEWERS SHOULD EDIT THE FOLLOWING WHEN THEY APPROVE**

- [ ] UX Design approved (tag @findimue for Web projects, or @kaiyuxu for Android projects, once ready for UXD review) 

- [ ] UX Writing approved (tag @danapj once ready for UXW review) 

**Design project is not complete until all of the above approvals are complete**

**Comment by seanlip** [comment]
@kaiyuxu Just wanted to flag this -- would you be able to take a look and suggest what a good follow-up would be? Thanks!

**Comment by kaiyuxu** [comment]
updated to both web and android design guides. can close this out.
