### ISSUE TITLE
[Translation Submitters] Translation Incomplete Message (sub-issue #6)

### ISSUE THREAD

**Issue by IMHieuVo** [oppia/design-team#67]
**Platform**
Oppia Web

**Describe the Request**
It is not always clear what is missing from a translation and how to fix it (e.g. concept cards).

![Image](https://user-images.githubusercontent.com/117132709/223325845-a5b06b1c-4f5e-41d6-97f8-2d7b9c831ae2.png)

**Context for the Request**
A subset of Submission Workflow #43.

**Link to PRD**
https://docs.google.com/document/d/1gzA9jJVlPt-DHxXwZXOQaoeN2mjFo8Qni0In193ypLI/edit

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by seanlip** [comment]
Here is the figma file with the changes:

https://www.figma.com/file/pGgmzgriNGSj4vtx7XvrlQ/Oppia-Issue-%2367?type=design&node-id=70%3A2&mode=design&t=h4NPPQNG3Ppwwkse-1

The main change is to replace the current message with "Translation is incomplete. Please use the Copy Tool to include any images or concept cards in the translated content". I am filing this fix on the developers' github and closing this issue. Thanks all!
