### ISSUE TITLE
[Translation Submitters] Translation Context (sub-issue #7)

### ISSUE THREAD

**Issue by IMHieuVo** [oppia/design-team#68]
**Platform**
Oppia Web

**Describe the Request**
It is not easy to access previous card for context on how a specific translation was made before, which can hurt translation consistency  (e.g. the translation for "stood on the dirt" is not obvious and it would be helpful to know how the previous translator did it in the previous lesson cards)

![Image](https://user-images.githubusercontent.com/117132709/223326059-a46f51cd-9cca-4389-9fe2-e377bf01e2ed.png)

**Context for the Request**
A subset of Submission Workflow #43.

**Link to PRD**
https://docs.google.com/document/d/1gzA9jJVlPt-DHxXwZXOQaoeN2mjFo8Qni0In193ypLI/edit

**Comment by seanlip** [comment]
@IMHieuVo Just to check, would you say this is the same as @DeeMoh21's project #52 , or a separate thing? I'm not totally sure about what the difference is.

**Comment by IMHieuVo** [comment]
@seanlip Very similar. This issue is technically the context of the **previous translation** whereas @DeeMoh21 project is context relative to the lessons. Or to put it another way, issue #68 is about seeing how the previous translation was done and issue #52 is about seeing where the card is within the lesson.

**Comment by seanlip** [comment]
Ah, that makes sense, thanks. I wonder whether, if we bring folks to the editor view, we could make it easy for them to see the translations attached to a card; that might it easier for them to "look around". But yeah, agreed that this is probably a separate project -- thanks!

**Comment by IMHieuVo** [comment]
Sean notes that this is technically not possible since there isn't there is a location for the 'previous translation'. It is also very common for the Translator to translate the lessons in order.
