### ISSUE TITLE
Web Onboarding

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#69]
https://docs.google.com/document/d/1r91ypya5HasdGsuLcuzt_utKik6xpIVe9koYGynl6kg/edit

Includes raising discoverability of language picker 

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by juliafalarini** [comment]
In progress. I have updated the mocks and created a second version of the [Research Plan](https://docs.google.com/document/d/1l5C-FmPeuzMwH0aBF2pal0lqyqaleBn6WxkLuZ9DOOE/edit?usp=sharing) and [Prototype](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?node-id=3521-27960), to test some improvements. One Outreachy contributor has already submitted a [report](https://docs.google.com/spreadsheets/d/1swIL-orNlcE-R6bqqDyb95vaN2zXZw56Dgzg5TrKaB4/edit?usp=sharing).

**Comment by juliafalarini** [comment]
Working on [hi-fi mocks](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194)

**Comment by seanlip** [comment]
@jikim322 @ConorMack @rfinch11 Could you please take a look at https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design&t=rX2OGatHaHf4LLVY-0 and leave comments / sign-off as needed, so that this can move to the development stage? Thank you!

**Comment by jikim322** [comment]
@juliafalarini Added a couple of comments for minor text edits. Once those are made, looks good for UXW!

**Comment by ghost** [comment]
Hi all,

I also added some comments. Thank you!

**Comment by rfinch11** [comment]
I've also added several comments, but I'd like to see resolutions before signing off from UXD

**Comment by juliafalarini** [comment]
Hi @rfinch11 @roxanashirazi @jikim322 and @seanlip. Thanks for your feedback! I've addressed/replied your comments!

Also, I'm having an issue with the body text style. I'm using the style from the Design Guide, but when I click to view the text style, the parameters are different (e.g. instead of a line height of 120% it's 20pt). 
I'm not allowed to change it, and when I click on "Go to style definition to edit", I'm redirected to the Design Guide file, where the parameters are correct, so there's nothing I can do. Does anyone have any idea how I can solve this problem?


![Image](https://github.com/oppia/design-team/assets/92189102/844fcd3c-5619-4624-846f-1592d1abc747)

**Comment by rfinch11** [comment]
@juliafalarini just to make sure I'm looking at the same thing, is this the file you're referencing? https://www.figma.com/file/nrQrOxSxSg1oabuVE6XJpa/Oppia-Design-Guide?node-id=430%3A2581&t=BjKbQWldwlIOrk44-0

When I look at the typography section of the Design System, I see the correct parameters (see screenshot below) 
<img width="1037" alt="Screen Shot 2023-07-18 at 12 35 50 PM" src="https://github.com/oppia/design-team/assets/17371709/9948ace2-9822-4c91-b7a9-772572a4f62a">

**Comment by juliafalarini** [comment]
Yes, this is the file I'm referencing, and it looks correct to me too. It just doesn't look correct in my file, even though it's referenced from the Design Guide file. @rfinch11

**Comment by rfinch11** [comment]
Got it. Very strange that it got corrupted in some way in your version. Want to try setting up a new file and bringing in the design system again to see if the same issue occurs?

**Comment by juliafalarini** [comment]
@rfinch11 yes, the same issue occurs in a new file :/

**Comment by juliafalarini** [comment]
Hi @rfinch11 @roxanashirazi @jikim322, did you get a chance to check my replies to your comments? we should finalize it asap so it can be moved to development. Thanks!

**Comment by jikim322** [comment]
@juliafalarini I think the only outstanding UXW item was the exclamation point in the CTA "Got it!" I made comments to remove/replace exclamation points from tooltip text and to keep in the CTA. I think once that's updated, it'll be good to go for UXW

**Comment by rfinch11** [comment]
Approved!

**Comment by seanlip** [comment]
The changes in this issue have been filed as separate issues on the GitHub developer issue tracker:
- https://github.com/oppia/design-team/issues/122: language selector screen
- https://github.com/oppia/oppia/issues/19214: splash page redesign
- https://github.com/oppia/oppia/issues/19215: signup flow, user type selection, preferences page changes
- https://github.com/oppia/oppia/issues/19216 (tangential): "save flow" on Preferences page
