### ISSUE TITLE
[Blog] Update on-site blog styling

### ISSUE THREAD

**Issue by dchen97** [oppia/design-team#70]
Take the new oppia.org/blog styling and existing functionality and just update the styling to be more modern / aesthetically pleasing and more consistent with the rest of the site

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by seanlip** [comment]
Note: the current blog is located at https://www.oppia.org/blog

**Comment by kmuir1991** [comment]
@seanlip does this need a UXW? Looks to be mostly UXD project, judging from the description.

**Comment by seanlip** [comment]
It's mainly UXD, but see my response to https://github.com/oppia/design-team/issues/86#issuecomment-1878031415.

**Comment by stepmalt** [comment]
A UXD note from when I was on the site earlier, usually on websites you are able to click the numbers to return to the pages. As of right now, I can only move between the pages via the arrows, not by clicking the numbers. I think that should be an interaction element added. Also, all of the content in each of the boxes is crammed into a tight space. It could do with some spacing, even just a bit.

**Comment by seanlip** [comment]
Thanks @stepmalt -- agreed. Just a note, re the page numbers, this is a bug that the dev team is working on fixing currently; you can see progress [here](https://github.com/oppia/oppia/issues/19403). Thanks for noticing it!

**Comment by ConorMack** [comment]
Project now available. 

Project started by a previous designer but not completed. View their [work here](https://www.figma.com/file/zz9fcrOqkje0Lhl6XnkO3S/Oppia_Update-on-site-blog-styling?type=design&node-id=0%3A1&mode=design&t=9Spcdef7o7vdulFU-1)

**Comment by suzieDev** [comment]
Hi Conor, I'd like to attempt this project if no one takes it. Thanks.

**Comment by stepmalt** [comment]
@suzieDev Let me know when you need another copy review on this!

**Comment by suzieDev** [comment]
> Let me know when you need another copy review on this!

yes, please. Thanks.

**Comment by seanlip** [comment]
Per discussion with Web design leads, closing this issue and merging it into https://github.com/oppia/design-team/issues/150 so that we can consolidate issues relating to the blog page.
