### ISSUE TITLE
Update the Android FAQ

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#75]
**Platform**
Oppia Android

**Describe the request**

Per [this comment](https://github.com/oppia/oppia-android/issues/4527#issuecomment-1226802693), we should take a look at our FAQ and ensure that it is what we want to present to users.

The aim of this issue is to audit the FAQ in the Android app and propose any changes that need to be made. We have not yet seen evidence that users use the FAQ, but in case they do, we would like to provide a structured experience that is structured coherently, answers their questions properly and is not misleading (e.g. details features that are not present within the app). Some additional questions that might be nice to answer include:

- Why are there only math lessons?
- Will you be making more lessons?
- I found a bug. How can I report it?
- How do I get the app in my language?
- How do I update the app?
- How do I update my Android OS? (see https://github.com/oppia/design-team/issues/62)

and possibly others.

**Context for the request**

This is an audit of an existing feature (the FAQ in the Android app).

**Link to PRD**
N/A

**Information about deadlines/priorities**
This can be tackled at the usual priority.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by seanlip** [comment]
Assigning to @danapj since this is mainly a UXW project.

**Comment by danapj** [comment]
@jlevick let me know if you would like this as a side project, and if you have an Android phone! This project might be easier if you can use the app

**Comment by jlevick** [comment]
@danapj I unfortunately don't have an Android phone, but if you think I can work on this without one I'll definitely take it as a side project!

**Comment by danapj** [comment]
@jlevick how would you like to work on this one together on the side? :D since it'll affect both our projects too! I have an Android phone so I could help with that side of things

**Comment by seanlip** [comment]
Just a note -- we might want to consider doing this a bit quicker. The current FAQ in the app is wrong, it has things like: "If changing your phone number: Enter your new phone number and tap **Verify**. A code is sent to confirm your new number. The code will expire after 5 minutes and must be entered in the new screen to be associated with your account." -- but we don't actually have that functionality in the app.

That said, not many users read the FAQ anyway. So there's an open question here about whether we want to actively try and make it more helpful, or keep this low-priority since it's not used that much. What do you all think?

**Comment by kaiyuxu** [comment]
I would focus on the core flows/ projects and make this lower priority... sounds like bug reporting can be part of the feedback flow. Will the first two questions on lessons be answered in the onboarding flow?

**Comment by seanlip** [comment]
> Will the first two questions on lessons be answered in the onboarding flow?

I'm not sure, but I don't think so -- though @tanzhirong (the PM) and @juliafalarini (the designer) would know better :)

**Comment by tanzhirong** [comment]
@seanlip Are the first 2 questions "_Why are there only math lessons? Will you be making more lessons_"? If so, correct, these are **not** addressed in the onboarding flow.

**Comment by seanlip** [comment]
Yup that's right, those are the first two questions. Thanks for confirming, @tanzhirong!

**Comment by danapj** [comment]
we'll be picking this up again sorry for the delay!

**Comment by jlevick** [comment]
Hi @seanlip, I'm not sure what the answers are to these Qs for the FAQ...is there somewhere I can find info around the answers, and then I can rewrite them to be more concise, clear, etc.? I've listed the ones I'm most unsure about below. Also unsure where to provide the answers to the Qs once they're written...would I just put them in another comment on this ticket? Thank you!

- **Why are there only math lessons?** 

- **I found a bug. How can I report it?** - _Would this be the feedback feature in the app?_

- **How do I get the app in my language?**  - _I know it's currently available in English and Brazilian Portuguese, but unsure what the answer might be?_

- **How do I update the app?**

**Comment by seanlip** [comment]
Hi @jlevick, here are some (very unedited) notes on the answers! I think you can just add the desired ones in another comment on this ticket, yup.

- **Why are there only math lessons?** This is because our mission is to help learners gain key skills that they need in life, and numeracy / basic math is a fundamental skill, so we started there. We are however planning to introduce new lessons soon on Science and other subjects, so check back regularly! 
- **I found a bug. How can I report it? - Would this be the feedback feature in the app?** Yep, see https://github.com/orgs/oppia/projects/7/views/9?pane=issue&itemId=18747855
- **How do I get the app in my language?** The app currently supports English, Brazilian Portuguese, Arabic and Nigerian Pidgin. The language list can be accessed using the side menu (I think it's through Settings?) We are interested in providing more languages, please contact XXX email address if you'd like to request that the app be available in your language.
- **How do I update the app?** Go to the Play Store and do that, just like any other app (we probably want to provide clearer instructions).

**Comment by jlevick** [comment]
Thank you @seanlip! Here is what I have, please let me know if you think anything needs editing. I don't have an Android phone, but Kate sent me her Figma file, so I _think_ these make sense. 

**- Why are there only math lessons?**
Oppia’s mission is to help learners gain necessary life skills. Math is an essential skill in everyday life. Oppia will be offering new lessons on science and other subjects soon!

**- Will you be making more lessons?**
Yes, Oppia will be offering new lessons on science and other subjects soon. Please check back for updates!

**- I found a bug. How can I report it?**
1. From your Oppia app home screen, tap the menu in the top left corner.
2. Tap **Share feedback**. 
3. Follow the instructions to report the bug or to share any feedback.

**- How do I get the app in my language?**
The Oppia app currently supports English, Brazilian Portuguese, Arabic, and Nigerian Pidgin. Choose one of these languages in the menu, under Options. To request the app in your language, please contact _email address_. 

**- How do I update the app?**

1. Open the Google Play Store app.
2. Tap the profile icon in the top right corner.
3. Tap **Manage apps and device**.
4. Locate the Oppia app. 
5. Tap **Update**.

I have not yet worked on the last question listed, _**How do I update my Android OS?**_ Also, github is changing my numbers into roman numerals, but for the devs: we would like numbers (1, 2, 3 etc). Thanks!

**Comment by kmuir1991** [comment]
Looks great on my end! Hopefully Sean can provide some feedback to ensure all the information given here is appropriate for what our users need to know.

One nit-picky editing comment: "Science" should be lowercase 🙂

Thanks Jaime

________________________________

**Comment by jlevick** [comment]
@kmuir1991 oops! Thank you for pointing that out! I'll edit it above :)

**Comment by seanlip** [comment]
Thanks! Took a look, and the only question  I have is about "How do I update the app?". The flow suggested takes me to a page where the only thing I can do is delete it :)

Maybe better to go to Play Store, search for the app and click Update?

**Comment by jlevick** [comment]
@seanlip ha! That is certainly _**not**_ what we want! It's been updated here :) I've also included copy for the last remaining FAQ question, **_How do I update my Android OS?_** Please let me know if you see anything else that needs to be corrected. Thanks! 

- **Why are there only math lessons?**
Oppia’s mission is to help learners gain necessary life skills. Math is an essential skill in everyday life. Oppia will be offering new lessons on science and other subjects soon!

- **Will you be making more lessons?**
Yes, Oppia will be offering new lessons on science and other subjects soon. Please check back for updates!

- **I found a bug. How can I report it?**

1. From your Oppia app home screen, tap the menu in the top left corner.
2. Tap **Share feedback**.
3. Follow the instructions to report the bug or share feedback.

- **How do I get the app in my language?**
The Oppia app currently supports English, Brazilian Portuguese, Arabic, and Nigerian Pidgin. Choose one of these languages in the menu, under Options. To request the app in your language, please contact us at _email address_.

- **How do I update the app?**

1. Open the Google Play Store app.
2. Search for the Oppia app. 
3. Tap **Update**.

- **How do I update my Android OS?** 

1. Tap your phone's **Settings** app.
2. Tap **System updates**.
3. Tap **System updates** and follow the instructions to update your Android operating system. 

Github is changing these numbers into roman numerals, but for the devs: we would like numbers (1, 2, 3 etc). Thanks!

**Comment by seanlip** [comment]
Thanks @jlevick! It looks pretty good, just two comments:

- I think, for the last question, the option is "System updates" on my phone, not "Systems updates". Is it "Systems updates" on yours? If so then we might need to make this more general, but I'm not sure.
- There are more questions in the current FAQ than just these. If we update the app to include the new questions and responses, what should the new order be for all the questions? Also, do you think the title "Featured Questions" in the app is correct?

**Comment by jlevick** [comment]
Hi @seanlip, I don't have an Android phone. I'll edit it above to say "system" vs. "systems" :)
In regard to the title "Featured Questions", I think _featured_ seems misleading as there are no other FAQs that are not featured. Perhaps "Common questions" would be more appropriate? Or even "Frequent questions" (would love your opinion if you have time, @kmuir1991 :)

@kmuir1991, do you know if the following are the only FAQs in the app as of now? I found them in the [IA Figma file](https://www.figma.com/file/cDBIjoKj7Dmevt22gUV7ix/Oppia---IA?type=whiteboard&node-id=45-10085&t=pduvwCbIJQZ0Lo6h-0):

- How can I create a new profile?
- How can I delete a profile?
- How can I change my email/phone number? 
- What is Oppia?
- Who is an Administrator? 
- Why is the Exploration player not loading? 
- Why is my audio not playing?
- I can’t find my question here. What now?

Lastly, do either of you know if there is any research the UXR team has done on which questions are searched for most? I'm thinking perhaps not as this initial ticket states there's not much evidence that folks are using the FAQ. I'll play around with the order of all Qs once I know if these (and the ones I wrote for) are all there are. Thanks!

**Comment by seanlip** [comment]
@jlevick Yup, the questions you mention match what I see in my version of the app :)

And yeah, I'm pretty sure the UXR team hasn't done research on this, for the reason you mention.

**Comment by kmuir1991** [comment]
Hi @***@***.******@***.***> !

-In regard to the title "Featured Questions", I think featured seems misleading as there are no other FAQs that are not featured. Perhaps "Common questions" would be more appropriate? Or even "Frequent questions" (would love your opinion if you have time, @kmuir1991<https://github.com/kmuir1991> :)

Yes, I agree that "Featured Questions" sounds a bit funky. I think "Common questions" should be fine here.


***@***.***<https://github.com/kmuir1991>, do you know if the following are the only FAQs in the app as of now? I found them in the IA Figma file<https://www.figma.com/file/cDBIjoKj7Dmevt22gUV7ix/Oppia---IA?type=whiteboard&node-id=45-10085&t=pduvwCbIJQZ0Lo6h-0>:

As far as I know, yes. What you listed is still what I see on my app, and what is current in the IA file.

I'm also not sure if UXR has any info on our users in regards to whether they're utilizing the FAQs. I think it'd definitely be worth it to ask.

@Sean ***@***.***> what do you think of the above?
________________________________

**Comment by seanlip** [comment]
No concerns re the above. (Re the last question, see my previous note in this thread.)

**Comment by jlevick** [comment]
@seanlip @kmuir1991 @roxanashirazi does anyone know why the current Qs are in the order they are? 
Thanks!

**Comment by seanlip** [comment]
There isn't a good reason. Feel free to reorder/reorganize/add/delete as you see fit. Thanks!

**Comment by jlevick** [comment]
Thanks @seanlip and @kmuir1991!
Here is the order I think makes the most sense. 

-  What is Oppia?
-  Who is an Administrator? 
-  How can I create a new profile?
-  How do I get the app in my language?
-  I found a bug. How can I report it?
-  Why are there only math lessons?
-  Will you be making more lessons?
-  Why is the Exploration player not loading? 
-  Why is my audio not playing?
-  How can I delete a profile?
-  How can I change my email/phone number? 
-  How do I update the app?
-  How do I update my Android OS?
-  I can’t find my question here. What now?

**Comment by kmuir1991** [comment]
Looks good to me!

Thanks Jaime!
________________________________

**Comment by seanlip** [comment]
Thanks @jlevick!

Just to check, do you want to make any changes to the answers to the existing questions? If not, I think this is probably enough info to send to the developer team...

**Comment by jlevick** [comment]
I think the Q **_How can I create a new profile?_** should be slightly updated, below is the current copy and updated suggestion:


Current
If it is your first time creating a profile and not have a PIN:

Updated:
If it is your first time creating a profile and you do not have a PIN: 


Otherwise I think it's fine! @seanlip

**Comment by seanlip** [comment]
Great, thanks! Moving this to the "handed off to PM" section, I'll get it filed when I'm back from travels.

**Comment by seanlip** [comment]
Filed as https://github.com/oppia/oppia-android/issues/5246. Thanks @jlevick and sorry for the delay on this!
