### ISSUE TITLE
Voice Over

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#8]
To prototype making voiceovers faster or slower, and perhaps do a demo or make a [technical design doc (TDD)](https://github.com/oppia/oppia/wiki/Writing-design-docs) describing the different options and pros/cons.

**Web links**
- [Voiceover Speed Rate Change Feasibility Study and Demo](https://docs.google.com/document/d/1X3sc6QO1Dkf7krWE-RlpvJhSGAO7iTjur7W0v8zAJ64/edit#heading=h.oy9fxlxijjqx)

**Checklist**
- Responsive Designs
  - [ ] XL Desktop
  - [ ] M Tablet
  - [ ] S Mobile

**Comment by seanlip** [comment]
Not ready for design team yet -- will reopen later when it is.

**Comment by fionafyzeng** [comment]
Is the email with the subject line _[Need help to review] PRD mock design: Improve App Listening to Study (voiceover) Experience_ related to Issue #8?

**Comment by seanlip** [comment]
No, this is separate. This issue #8 is for the Web, and the other email is for voiceovers and Android.

**Comment by seanlip** [comment]
Superseded by #46. Closing.
