### ISSUE TITLE
Confusing progress/info card

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#80]
**Platform**
Oppia Web

**Describe the request**
From learner feedback (2 reports):

*Progress card info is not understood by student* (this refers to the "Lesson Info" card).

The student does not understand any information on the screen. She says the icons conveys no meanings to her and she does not understand how much progress she has made from the Learning Progress Bar (There are 6 chapters in Precentages but only four numbers are showing). All the icons are strange to her. She also did not know how to exit this progress card.

See screenshot below.

![Image](https://user-images.githubusercontent.com/10575562/232753751-36608e7d-06eb-40c9-a68f-5018a9cb7c6b.png)

**Context for the request**
This is for a student using the mobile website. They reach this view by clicking on the Lesson Info text in the footer.

The issue was reported for a learner on a mobile device, but the problem also shows up in desktop view.

**Link to PRD**
N/A

**Information about deadlines/priorities**
This can be tackled at the usual priority.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by juliafalarini** [comment]
This has been resolved in the Lesson Player Redesign project @ConorMack. We no longer have this progress info card in the new version of the lesson player.

**Comment by ConorMack** [comment]
Thank you for letting me know!

**Comment by seanlip** [comment]
Closing this per @juliafalarini's comment since no further action is needed.
