### ISSUE TITLE
Non-Google Accounts on Oppia

### ISSUE THREAD

**Issue by yupigummy** [oppia/design-team#81]
**Platform**
Oppia Web 

**Describe the request**
UXW and UXD help needed for PRD on Oppia accounts created with Non-Google emails

**Context for the request**
Today, users (learners and contributors) can only create Oppia accounts using a Google account. This is a new feature allowing users to create Oppia accounts using other email addresses, increasing the accessibility to more users. 
You can see this at https://www.oppia.org/ > "SIGN IN" on the top right corner

**Link to PRD**
[PRD Non-Google Accounts on Oppia](https://docs.google.com/document/d/1TDi8jsXbfUVZak_FQfR6gLplDK5m_zG1Y4Tze1ZIDoE/edit?usp=sharing)

**Information about deadlines/priorities**
High priority as this is a key accounts feature
Target due date: May 30, 2023

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by yupigummy** [comment]
Note: To take note of changes in web onboarding project https://github.com/oppia/design-team/issues/69 and ensure no contradicting design 

I think the only overlap is post signing up, the user should be redirected to the new "Complete sign up" page as shown in the [figma mock for web onboarding](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design)

**Comment by rfinch11** [comment]
Great work @cwg421 and @FuyiY! you have my sign off as soon as the final comments have been resolved.

**Comment by yupigummy** [comment]
Marking as signed-off from product. 

Just one minor update to be made and we’re good to go ([see comment on Figma](https://www.figma.com/file/vITLZY8f7gLsrmf4arUpDL?node-id=944:30164&locale=en&type=design#544580650))

Thanks so much for your hard work @cwg421 and @FuyiY!

@jikim322 / @roxanashirazi could you do a final review and provide your sign-off as well?

**Comment by ghost** [comment]
Done. Great job, Team!

**Comment by yupigummy** [comment]
FR raised to Eng team: https://github.com/oppia/oppia/issues/18878

Thanks everyone for all your hard work!
