### ISSUE TITLE
Contributor Dashboard Information Architecture

### ISSUE THREAD

**Issue by IMHieuVo** [oppia/design-team#82]
**Platform**
Oppia Web

**Describe the request**
The information architecture of the website, especially the contributor dashboard flow, can be confusing for new designers to navigate. The intent of this project is to create a visual information architecture flow for the Contributor Dashboard and allow designers to use it as a base to understand how their project fits into the bigger picture.

**Context for the request**
The website currently does not have a complete information architecture mapping. 

**Information about deadlines/priorities**
While this issue is not time-sensitive, completing this would be tremendously helpful for other designers to visualize the flows.
Once this is completed, it can be periodically updated to include new flows.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorAMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by kmuir1991** [comment]
[https://www.figma.com/file/cDBIjoKj7Dmevt22gUV7ix/Oppia---IA?type=whiteboard&node-id=0-1&t=PuqFtZXQqLRFt2C0-0](https://www.figma.com/file/cDBIjoKj7Dmevt22gUV7ix/Oppia---IA?type=whiteboard&node-id=0-1&t=PuqFtZXQqLRFt2C0-0)

Does this cover what we're looking for here?

@IMHieuVo @celestinetales @seanlip

**Comment by seanlip** [comment]
@kmuir1991 I'm not sure, sorry -- will need to defer to @IMHieuVo and @celestinetales on this.

**Comment by kmuir1991** [comment]
@IMHieuVo @celestinetales can one or both of you please review the file in the comment I left above and clarify whether it covers what we need here?

**Comment by IMHieuVo** [comment]
Yes, this is what we were looking for. Now the team can technically use this as a tool to pin point potential pain points.

**Comment by kmuir1991** [comment]
@IMHieuVo cool! 

@seanlip I've changed the status to "Handed off to PM" just to be safe, but I think we can actually mark it as completed.

**Comment by seanlip** [comment]
Yup that's fine since this is design-internal. Marking as completed and closing ,thanks!
