### ISSUE TITLE
Partnerships page update

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#84]
**Platform**
Oppia Web

**Describe the request**
The partnerships team is working on an updated version of the Partnerships page to include more information about partners/testimonials/etc. We have some previous work on this which hasn't been implemented yet -- see https://github.com/oppia/oppia/issues/17433. The new mocks are being worked on in https://www.figma.com/file/4qUxLmL1dRCyDqudLE93uZ/Oppia-Design?type=design&node-id=341%3A56&t=E7WeLRG9GWt9bECj-1.

This issue is opened to track that request and confirm that it meets Oppia's design standards and can be added to the website. If so, this can supersede [#17433](https://github.com/oppia/oppia/issues/17433).

**Context for the request**
This is an existing feature. It is needed so that NGO partners have a page that enables them to understand what services Oppia provides and how they can get in touch with us. The existing page is at https://www.oppia.org/partnerships which is somewhat sparse on content.

**Link to PRD**
There is no PRD for this project -- the request comes directly from the Partnerships/Outreach team.

**Information about deadlines/priorities**
It would be helpful to do this soonish since it's important for follow-on partnerships work (that e.g. involves directing folks to the website in our awareness and outreach efforts).

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved
- [x] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @seanlip (PM)

**Comment by OSETIEMORIA** [comment]
I would like to work on this.

**Comment by OSETIEMORIA** [comment]
Hi @ConorMack @rfinch11 @jikim322 @roxanashirazi I wanted to let you know that I've completed the issue of updating the partnerships page. You can find the designs at https://www.figma.com/file/4qUxLmL1dRCyDqudLE93uZ/Oppia-Design?type=design&node-id=341%3A56&t=E7WeLRG9GWt9bECj-1 

Could you please take a moment to check out the designs and provide your approval for development? Your input is valuable and will ensure that we're aligned before moving forward.

Looking forward to your thoughts!

**Comment by rfinch11** [comment]
Updated file here: https://www.figma.com/file/G9SAOAVh8NBc5qCApx4qOw/Partnership-Page-Redesign?type=design&node-id=1%3A462&mode=design&t=DszdFfM989lq2FUK-1

**Comment by ghost** [comment]
Great work on the designs!

I added some preliminary comments on the UXW.

**Comment by ghost** [comment]
Added some comments to the Figma file.

**Comment by kmuir1991** [comment]
@OSETIEMORIA @stepmalt 

I think we're pretty close to wrapping this one up. There are just two UXW-related comments left that need to be addressed on the Figma.

Can we please address these so we can close this issue? We just need UXW lead sign off at this point.

Thanks all!

**Comment by OSETIEMORIA** [comment]
Hi @kmuir1991 I've gone ahead to implement one of the comments. @stepmalt Could you please check the other one out?

Thanks.

**Comment by kmuir1991** [comment]
@OSETIEMORIA hi! Since there is only one unresolved comment on the file and it doesn't appear to be a huge issue, I'm going to say we're good to wrap it up.

**Comment by OSETIEMORIA** [comment]
> @OSETIEMORIA hi! Since there is only one unresolved comment on the file and it doesn't appear to be a huge issue, I'm going to say we're good to wrap it up.

Thanks Kate.

**Comment by seanlip** [comment]
Sorry for the delay on this. The mocks have been updated [here](https://github.com/oppia/oppia/issues/17433) and I am going to close this issue since the design is completed. Thanks @OSETIEMORIA!

**Comment by OSETIEMORIA** [comment]
No problem, thank you for the update.

**Comment by S4v8n** [comment]
Design file has been transferred over to the Oppia figma account: access file [here](https://www.figma.com/design/uBHubRHcwTYgnY5wm2uRng/Partnership-Page-Redesign?node-id=0-1&t=n5JY6qFK3EvLStcq-1).
