### ISSUE TITLE
[UXW] Audit the current welcome email that Oppia.org sends on signup

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#89]
**Platform**
Oppia Web

**Describe the request**

When a user signs up to Oppia Web, we send them an email (see below for a copy of the email text).

This hasn't ever gone through UXW review so I wanted to send it for an audit. 

One additional suggestion: in our new [onboarding mocks](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design&t=r7ltFKv84pYZdO70-0), users can choose whether they are a learner, teacher/parent, contributor, or lesson creator (or some combination of the above). I can think of two ways to handle this:

1. For the "pointers" section of the email, have a list of bullet points (at least 3 for each of these cases), and rank them in order of priority. We'll then pick the top 3 that apply to that user to put in the email. For example, if a user says they're both a teacher and a contributor, we'll look at the first 3 bullet points tagged with those user types, and use those.
2. Alternatively, we give the different "roles" a priority order. When a user signs up, we take their primary role and send them an email crafted for that role. We ignore any other roles that a user has chosen when sending that email.

There may be others -- as long as it's clear what email to send to a particular user, I'm fine with whatever UXW suggests.

**Note**: It might actually be better to have a Welcome email "sequence" (i.e. not one email, but several). Some examples for inspiration: https://blog.hubspot.com/marketing/welcome-email-examples

-------
**Email text:**

<p>Welcome to Oppia.org, and thanks for joining us in our mission to make learning free and accessible to all!</p>

<p>Here are a few pointers to help you get started:</p>
<ul>
  <li>Check out our free, interactive math lessons at https://www.oppia.org/learn/math .</li>
  <li>Browse <a href="https://www.oppia.org/community-library">the community library</a> to see lessons created by members of the community.</li>
  <li>Support education for all by <a href=”https://www.oppiafoundation.org/volunteer”>volunteering</a> or <a href=”https://www.oppia.org/donate”>donating</a> to the project.</li>
</ul>

<p>As a non-profit, open-source project, Oppia depends on your thoughts and ideas to thrive. Feel free to let us know if you have any feedback, and don’t forget to connect with us on social media!</p>

<p>Thanks,</p>
<p>The Oppia Team</p>

-------

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [X] UX Writing approved
- [ ] Product approved

**Comment by seanlip** [comment]
@jikim322 @roxanashirazi Would either of you be interested in taking this up?

**Comment by jikim322** [comment]
Hi! Sorry for the late reply -- yep, I can work on this this week.

**Comment by seanlip** [comment]
Great, thanks @jikim322! Assigned you.

**Comment by seanlip** [comment]
@jikim322 FYI I added an edit to the description, suggesting that a welcome email **sequence** might be better:

> Note: It might actually be better to have a Welcome email "sequence" (i.e. not one email, but several). Some examples for inspiration: https://blog.hubspot.com/marketing/welcome-email-examples

Perhaps this is something that we could investigate.

**Comment by kmuir1991** [comment]
Hi @jikim322 ! Any updates on this issue? Is it still being worked on? Sean and I noticed that it's been stagnant for a while.

**Comment by jikim322** [comment]
Hi @Kate Muir ***@***.***>! This was one of the unfinished
projects I emailed you about before my break in the fall. Should have
checked in about it -- I think I thought it would be transferred to someone
else in my absence. I will get back on it and hopefully have some updates
by next week.

Thanks!
Ji

**Comment by jikim322** [comment]
Hi @seanlip  and @kmuir1991! 
Finally got into looking at this email a bit more and reviewing some of the inspo emails from Hubspot, and have a lot of questions to start: 

- Do we have data on how often people click the hyperlinks in the email? 
  - If so, what’s most often opened? 
- What is the user journey before a user creates/signs up for an account? 
  - I signed in with Google to see how things would look when I first started volunteering, but how do others typically get there?
  - Would a volunteer typically sign up before they fill out the volunteer form? 
  - Do learners sign up for Oppia web on their own or is the typical path that they are directed by an educator?
- I do think each profile type is too distinct to have one catch-all welcome email and agree with your note about maybe having a sequence of emails (1. more general welcome then 2. next best steps for profile type). 
  - If we go this route but still want to make a content recommendation in the first welcome email, what should it be? 
    - Math library for oppia curated courses would probably be the strongest rec for a learner.
    - Community library would probably be strongest rec for the contributor.
    - But would these be a bit too in the weeds to start?
- Once the account registration flow (that Julia worked on) is live, will all users receiving a welcome email have gone through that registration flow and have had some exposure/understanding of the different profile types?

**Comment by seanlip** [comment]
@jikim322 Thanks for your questions, sorry for the late reply on this! Answers below:

- No, we don't have this data (sorry).
- The planned user journey (going forward, not live yet) is what's described in [these mocks]( https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design&t=v3mhfxAkI0l9V53z-0), so let's design with that in mind. (Currently I think users just see the sign up button at the top right and click it; I believe we also show it to them after they finish their first exploration as a guest.) Typically volunteers don't sign up unless instructed to do so as part of the volunteer onboarding process. I think learners may sign up on their own or as directed (if they are using Oppia within a school/class setting).
- I agree that the math library is the strongest rec for a learner. For contributors I would take them to the contributor dashboard, not the community library.
- Yes, once the account registration flow is live, all users receiving a welcome email will have gone through that registration flow and we'll know that their chosen profile types are at the point of sending the welcome email.

Hope this helps! Please feel free to ask if you have any follow-up questions (and, if I take more than 2 days to respond, feel free to follow up by email). Thanks!

**Comment by jikim322** [comment]
Awesome, thanks @seanlip! I'm going to set 1/10 as a next milestone to have some potential email drafts for these.

**Comment by jikim322** [comment]
@kmuir1991 @seanlip Drafts for emails are ready for review here: https://miro.com/welcomeonboard/S3VMbXB3VDU1eE5aYkVPbzliWU9EUGloNmkwZnJsWDFUaFlzNWd6TnEwZzhweXFYSVRrdE9FUldyMXpmd3JCRXwzNDU4NzY0NTE1Njg4MzU0MzI3fDI=?share_link_id=606475733738

Added red stickies for where to review! Let me know if you're having any issues accessing.

**Comment by kmuir1991** [comment]
Hi @jikim322 !

These look fantastic, thank you so much for your dedication to this project!

I left a few comments for review :)

**Comment by jikim322** [comment]
@kmuir1991 thanks for your comments! responded to a couple and will make your language edit suggestions on next iteration. @seanlip if you could also review, that would be great!

**Comment by seanlip** [comment]
Miro guest link for reference: https://miro.com/app/board/uXjVN6pIzkc=/

**Comment by jikim322** [comment]
Updated email drafts: [](https://docs.google.com/document/d/1Uwmjgp-16Iu4rclNpzTFrNA8qNUx2ZVQtrFSoRZWs80/edit?usp=sharing)

**Comment by jikim322** [comment]
Revised versions of emails with notes: (https://docs.google.com/document/d/1Uwmjgp-16Iu4rclNpzTFrNA8qNUx2ZVQtrFSoRZWs80/edit?usp=sharing)

**Comment by seanlip** [comment]
Thanks @jikim322, sorry for the delay. I noticed a few typos that we should clarify before this gets implemented -- requested access to the doc so that we can get them resolved before sending to the dev team. Thanks!

**Comment by seanlip** [comment]
Also I noticed this hasn't been UXW approved yet so I'm moving it back to "waiting on UX lead approval" first. Note that only UXW and product approval is needed for this project. Thanks!

**Comment by seanlip** [comment]
(To be specific: @kmuir1991 @stepmalt could you PTAL for UXW? Then you can change the status to "handed over to PM" once your review is complete and you've ticked the checkbox at the top of the issue. Thanks!)

**Comment by kmuir1991** [comment]
@seanlip I can do this. 

@jikim322 can you please link me to the most updated mock for this? Iirc, we switched from Miro to something else recently.

**Comment by jikim322** [comment]
Yep! here is the link: [emails in google doc](https://docs.google.com/document/d/1Uwmjgp-16Iu4rclNpzTFrNA8qNUx2ZVQtrFSoRZWs80/edit?usp=sharing)

FYI I'm making a couple of additional edits based on Sean's last review.

**Comment by kmuir1991** [comment]
@jikim322 thanks!

If you're still make edits, would it make more sense to have me review this when those are done?

**Comment by jikim322** [comment]
@kmuir1991 emails are aready for your review [here](https://docs.google.com/document/d/1Uwmjgp-16Iu4rclNpzTFrNA8qNUx2ZVQtrFSoRZWs80/edit?usp=sharing). Left comment threads in there but will clean up and resolve once it gets your approval!

**Comment by kmuir1991** [comment]
Thanks @jikim322 ! Looks great. Approved on my end

@seanlip not sure why but I don't seem to be able to click the checkbox for "UX Writing approved"

**Comment by seanlip** [comment]
@kmuir1991 Weird, I couldn't check it either. I updated it manually, thanks! I will do the other follow-ups during my usual PM triaging round next week.

And thanks @jikim322 for all your hard work on this!

**Comment by jikim322** [comment]
@seanlip Thanks -- there are a couple of comments from marketing that are outstanding. I'll work on wrapping those up. I did ping you about one comment. [Heres the link](https://docs.google.com/document/d/1Uwmjgp-16Iu4rclNpzTFrNA8qNUx2ZVQtrFSoRZWs80/edit?usp=sharing) for easy reference.

**Comment by seanlip** [comment]
Thanks @jikim322!  I replied to your comment.

**Comment by seanlip** [comment]
An update: I have filed this as part of the existing issue https://github.com/oppia/oppia/issues/19215 . Closing as fully complete -- thanks @jikim322!
