### ISSUE TITLE
Make progress bar consistent in new lesson player mocks.

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#90]
**Platform**
Oppia Web

**Describe the request**

@ningz2 mentions in https://github.com/oppia/oppia/issues/18247:

In the [Lesson Player project](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6912%3A366002&mode=design&t=Z8BPhqp6GpmmZbaT-1), it seems like the progress bar on the "Exit" pop-up window is not consistent with the graphic on Checkpoint project, so I'd like to coordinate on this point.

The aim of this issue is to do the necessary coordination and make any changes to the Figma files so that the design team as a whole has a single idea of what they plan to do here.

**Context for the request**

This was brought up as part of a discussion in https://github.com/oppia/oppia/issues/18247. It is not a technical issue so I am filing it here.

**Information about deadlines/priorities**

This should be sorted out before any development work happens on Julia's lesson player mocks or the checkpoints mocks (if not integrated with Julia's).

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)

**Comment by juliafalarini** [comment]
If it's only about adding the phone number and email to the dialog box, I can do that very quickly. If there is anything else that needs to be reviewed, please clarify @ningz2 @seanlip. Thanks!

**Comment by seanlip** [comment]
Thanks @juliafalarini. @ningz2  -- I'm filing this issue based on a comment you left on the other one. Could you please clarify what is required in order for this issue to be resolved?

Thanks!

**Comment by seanlip** [comment]
Per @ningz2 and @juliafalarini -- they'll file another issue replacing this one with more details. Closing this one in the meantime.
