### ISSUE TITLE
Checkpoints improvements -- simplify display of checkpoints in chapter cards on topic page

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#91]
**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @seanlip  (PM)
- CD projects: @IMHieuVo / @celestinetales (UXD), @kmuir1991 / @12lamy2 (UXW), @dchen97 (PM)
- Android projects: @kaiyuxu (UXD), @jlevick / @danapj (UXW), @seanlip (PM)

**Comment by seanlip** [comment]
Hi @juliafalarini -- just to check, this is part of your current project, right? Asking since it was previously assigned to @ningz2 but you will be delivering the final version?

/cc @ConorMack

**Comment by juliafalarini** [comment]
Yes, it is!

**Comment by kmuir1991** [comment]
@seanlip @juliafalarini unsure as to whether or not this project still needs UXW assistance, but since Roxana is no longer with Oppia, I'm going to assign myself instead since I have also worked closely on the project.

**Comment by seanlip** [comment]
I think this is folded into Julia's big project actually -- https://github.com/oppia/design-team/issues/97 . Let's just make sure that this is addressed properly as part of that.

**Comment by juliafalarini** [comment]
Yes, this was addressed in the project #97

**Comment by seanlip** [comment]
Thanks! Closing this as a duplicate then.
