### ISSUE TITLE
[Topic page] Add Pop-up Window for Choosing to Start Over or Review a Completed Lesson on Topic Page

### ISSUE THREAD

**Issue by ningz2** [oppia/design-team#92]
**Platform**
Oppia Web 

**Describe the request**
Create a pop-up window for completed lessons on the Topic page to let users choose to start over the lesson or review the lesson with correct answers.

**Context for the request**
- The window will pop up when users click on the "Review" button on completed lesson cards. If users choose to "start over", the lesson progress will return to zero, and users will not see previous answers when taking the lesson. If users choose to just "review", they will see all previous correct answers when going over pages in a lesson.

**Link to PRD**
N/A

**Information about deadlines/priorities**
This can be tackled at the usual priority. It would be good to start this project based on the new Topic page that Julia will be working on.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by seanlip** [comment]
Folded into https://github.com/oppia/design-team/issues/107 per discussion with the Web UX design leads.
