### ISSUE TITLE
Add Email and Text Options to Remember Learning Progress for Unregistered Users

### ISSUE THREAD

**Issue by ningz2** [oppia/design-team#94]
**Platform**
Oppia Web

**Describe the request**
Add email and text options aside from copying the link to remember lesson progress for unregistered users on the "Save Progress" Pop-up window. 

**Context for the request**
- This is an add-on project based on the current "Save Progress" window
- Current unregistered users can only copy the text format of links to save their temporary progress. Adding email and text options is to prevent users from losing the learning progress link.

(Note: If you have further questions about this project, feel free to contact @juliafalarini for context or more info. Thanks!)

**Link to Former Design of email and text options**
[Former design](https://www.figma.com/file/NRJaGClL9EUJBAhugi4oPQ/Oppia-User-Checkpoints?type=design&node-id=2215%3A8360&mode=design&t=xVkbvG8iB8Pk1z53-1)
[Current design of the Save Progress window](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6912%3A365831&mode=design&t=9t6uVpWFzxHUZFVP-1)

**Information about deadlines/priorities**
This can be tackled at the usual priority, but it would be good to hand-off with the current Save Progress window design

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved (Android mocks should include dark mode)
- [x] UX Writing approved
- [x] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by seanlip** [comment]
Deassigning @juliafalarini since she's not working on this.

**Comment by jikim322** [comment]
Hi @qluuu ! I'm the UXW for this project. I see right now it says you're still waiting on results from UXR but let me know if/when you need me to review.

**Comment by qluuu** [comment]
Hi @jikim322 Thanks for reaching out and following-up with me. Yes, the project is still with UXR. I will of course keep you in the loop if I have any updates from that front. We can do a more in-depth UXW review/discussion when I iterate based on the UXR results. In the meantime, if you would like to familiarize yourself with the process so far, please feel free to view the UXW-related comments on the "Lo-Fi Wireframe [Desktop]" page in the Figma file as well as the "Hi-Fi Wireframe Vr.3 [Desktop]" page which is the most current iteration of the design. Thanks again!

**Comment by qluuu** [comment]
Hi @jikim322 I hope you are doing well. Just wanted to give you a quick ping here to let you know that I have received my UXR results, and I have iterated on my hi-fis for both mobile and desktop. 

I would love your input from the UXW side of things on the copy for these screens. I have sent a team update email today with you cc'ed. For quick reference, here is the [figma link](https://www.figma.com/file/KsHy1wEPv3Ockq02owVAt8/Oppia-%2394-Add-Email-and-Text-Options-to-Remember-Learning-Progress?type=design&node-id=304%3A4225&mode=design&t=rKW7BhtnlzPpISw8-1) to the newest iteration for your review. 

Thank you! Looking forward to speaking with you further.

**Comment by jikim322** [comment]
Thanks, Queena! Sorry for the late response — I’ve been sick the past
couple of days. I’ll try and take a look today!

**Comment by qluuu** [comment]
@jikim322 I hope you are feeling better! Thank you for your feedback. I've reviewed your comments and will reply + start making changes this weekend. Re: Snack Bar Error Messages, I will be making some variants for this component to reflect more actionable copy (I was thinking one for network connection error and one for email format error). Thanks again!

**Comment by qluuu** [comment]
@jikim322 Just have a quick update for you. I've made some more actionable copy toasts (I was also trying to keep these messages concise/limited to one line) for your review and also edited the header and sub-header section. Would love to know your thoughts. UXW parts are labeled with yellow annotation boxes. Thank you!


Here is the figma page link for quick reference: [https://www.figma.com/file/KsHy1wEPv3Ockq02owVAt8/Oppia-%2394-Add-Email-and-Text-Options-to-Remember-Learning-Progress?type=design&node-id=376%3A2196&mode=design&t=wYgN2RNTV3MPdNBO-1](url)

**Comment by qluuu** [comment]
Hi @jikim322 just wanted to bump this in your inbox. When you have availability, please check up the updated UXW changes. Thanks again, and have a great weekend!

**Comment by jikim322** [comment]
Sorry for the delay, Queena! Will try to review by today, tomorrow at the
latest!

**Comment by jikim322** [comment]
I've reviewed the latest copy and left a couple of comments! It looks great!

**Comment by qluuu** [comment]
Great thank you @jikim322 ! I will go over your comments this week and make adjustments as needed. :)

**Comment by stepmalt** [comment]
UXW approved.

**Comment by seanlip** [comment]
@qluuu @celestinetales Could you PTAL at this for design systems and, once approved, hand over to product? Thanks.

**Comment by qluuu** [comment]
@seanlip I've approved it from the design systems side of things and have updated the checkbox in the github description and changed the status to PM Review. Thank you!

**Comment by seanlip** [comment]
Filed as https://github.com/oppia/oppia/issues/21063. Thanks all!
