### ISSUE TITLE
Provide indicators to the learner to let them know when content in a lesson has been auto-translated.

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#95]
**Platform**
Oppia Web

**Describe the request**

We want to provide lessons on Oppia in different languages, to account for the fact that many learners around the world are not familiar with English. To this end, we are planning to use auto-translations to temporarily fill gaps in lesson translations.

Because these auto-translations may not be entirely accurate, we want to ensure that the learner clearly understands this. This corresponds to point 3 in the "summary of the proposed solution" section of this PRD: https://docs.google.com/document/d/1TeGQQNLNJWkTgvGQ1xmV6snz8zXnJ23TvuDKtK5_Tok/edit

**Context for the request**

This is a new feature that builds on the updated exploration player design by @juliafalarini in https://github.com/oppia/design-team/issues/58. Mocks should be based on this version of the lesson player rather than the current version that is available on the Oppia website.

**Link to PRD**
https://docs.google.com/document/d/1TeGQQNLNJWkTgvGQ1xmV6snz8zXnJ23TvuDKtK5_Tok/edit (see point 3 in the "summary of the proposed solution" section).

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved
- [x] UX Writing approved
- [x] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack / @rfinch11 (UXD), @jikim322 / @roxanashirazi (UXW), @dchen97 (PM)

**Note:** When this project is completed, the mocks should be added to this issue on Oppia-web: https://github.com/oppia/oppia/issues/18767

**Comment by liwei899** [comment]
Hi Team, 

I hope you're all doing well. I wanted to share the progress I've made regarding the auto-translation issue. I've spent some time scratching the surface and brainstorming ideas for potential solutions.

I've summarized my initial thoughts and sketches in the attached Figma link: [Figma Auto-Translation Ideation](https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=0%3A1&mode=design&t=UtRGqBiFWRMntxmo-1).

Please take a look and provide your feedback. I'm particularly interested in hearing your thoughts on the feasibility and potential effectiveness of the proposed approaches. Let's collaborate and refine these ideas together.

Looking forward to your input.

Best regards,

**Comment by liwei899** [comment]
I wanted to discuss a critical aspect of the project we're currently working on, specifically related to the addition of a status indicator for translated and auto-translated content. I appreciate the opportunity to work on this, and I believe clarifying the proportion between these two types of content on page #95 is key to making the right design decisions.

From my understanding, learners encounter content that is both translated and auto-translated. It's great that there's an indicator to differentiate between the two, but what we need to determine now is how much of the content on a single page comprises each type. Are the translated and auto-translated portions separate, or are they mixed within the same page?

Understanding this breakdown will significantly influence the design of the status indicator. If the content is mixed, we might need a dynamic indicator that changes as learners scroll through the page. On the other hand, if the translated and auto-translated sections are separate, we could opt for a clearer, more distinct indicator to ensure learners are aware of the shift.

Could you please provide some insight into the proportion and distribution of translated and auto-translated content on page #95? This information will be invaluable as we move forward with the design process. Additionally, if you have any preliminary ideas or preferences regarding the indicator's appearance and behavior, I'd love to hear them.

Thank you again for assigning me this task, and I'm eager to ensure that the indicator we implement enhances the learning experience. Your guidance in this matter will be greatly appreciated.

**Comment by liwei899** [comment]
Second version after receving feedback to Suzie https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=28%3A1119&mode=design&t=D3karwNbZ4AWhAun-1 
Feel free to leave any feedback or comment. Thank you.

**Comment by seanlip** [comment]
Hi @liwei899, sorry for the late reply. Here is a response to the main question you asked:

> From my understanding, learners encounter content that is both translated and auto-translated. It's great that there's an 
indicator to differentiate between the two, but what we need to determine now is how much of the content on a single page comprises each type. Are the translated and auto-translated portions separate, or are they mixed within the same page?

Content in the lesson player is separated into different types. There is the main content, which is what Oppia tells the learner. There is the feedback Oppia gives when the learner enters a specific answer. There are hints/solutions which Oppia shows when the learner is stuck. There is also some text in the questions (e.g. multiple-choice options). It is possible for any of these to be translated or not -- and if we don't have a human-contributed translation for it then we might use an automatic translation.

So, the general answer is that they are likely to be mixed within the same page. I hope this helps!

**Comment by liwei899** [comment]
https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=55%3A1931&mode=design&t=mAlaIyRGnDyHnpbe-1 

Hi all,
Please leave feedback for the highlighted part of version 3. Thank you.

@seanlip @ConorMack Hi Conor, can you share the group email list with me as we discussed in the meeting yesterday? Thank you.

**Comment by liwei899** [comment]
Hi @seanlip, thanks for explaining the structure to me. It's clearer.

**Comment by liwei899** [comment]
Version 4: 
https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=93%3A1310&mode=design&t=uy62zwOmrwOxnof4-1

**Comment by liwei899** [comment]
Version 5 https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=123%3A1085&mode=design&t=WMwxge6uENfMaoqV-1

**Comment by liwei899** [comment]
Dear Team,

I hope this email finds you well. I wanted to provide you with some crucial information regarding the upcoming Version 7 update. This update keeps optimizing our notification bar, which will enhance the user experience and improve our overall product functionality.

Section 1: One-Time Disclaimer

A one-time disclaimer that will be shown to all learners when they first start a new learning content and encounter the new notification bar. This disclaimer is designed to ensure transparency and inform users about the auto-translation. It is crucial to manage the learners' expectations effectively during this transitional period.

Section 2: Two Options of the Notification Bar (Pending Testing Plan Approval)

I have incorporated two options for the new notification bar design, pending the approval of our testing plan. These options are as follows:

Option A: The notification bar will feature a sleek, compact design at the top of the user interface. It will include an option for users to manually close the notification if they wish.

Option B: The notification bar will be positioned at the top of the screen, but allowing for higher visibility with one of the accent colors- orange.  Users can manually close the notification, as in Option A.

The testing plan, currently under review, will help us gather valuable feedback and data to make an informed decision on which option to implement. I am excited to hear your thoughts and will keep you updated once the plan is approved.
The prototype link is here: [Two Notification Bar Testing](https://www.figma.com/proto/VlT6bJqNQkH2H18ERvXGIk/Oppia?page-id=187%3A3186&type=design&node-id=187-3190&viewport=639%2C442%2C0.13&t=F0P9SPx2fYgFJoKY-1&scaling=min-zoom&starting-point-node-id=187%3A3190&show-proto-sidebar=1&mode=design)

Section 3: What Happens When the User Manually Closes the Notification or Doesn't

Once the user encounters the new notification bar, they will have the option to manually close it. If they choose to do so, they can always access the information in the notification through our in-app "Notifications" section. If users decide not to close the notification, it will remain visible within five seconds. 

To explore the changes and view both notification bar prototypes, please follow this Version 7 Link. Additionally, you can access them via the following link: [Chose Button](https://www.figma.com/proto/VlT6bJqNQkH2H18ERvXGIk/Oppia?page-id=187%3A3186&type=design&node-id=187-4285&viewport=639%2C442%2C0.13&t=F0P9SPx2fYgFJoKY-1&scaling=min-zoom&starting-point-node-id=187%3A3191&show-proto-sidebar=1&mode=design)

I encourage you to test both prototypes and provide your feedback to help me make an informed decision on the final design. Your insights and suggestions are invaluable to me.

If you have any questions or concerns, please do not hesitate to reach out.  

Thank you for your continued support and dedication to improving our product.

Best regards,
Liwei

**Comment by stepmalt** [comment]
Is this the most recent iteration? I don't think it is, but I want to make sure I'm looking at the copy for the most recent. If it is, then I'll comment on it from Liwei's last post on 10/7. I just thought there were further iterations, and I want to make sure I'm collaborating on the most current.

**Comment by seanlip** [comment]
@stepmalt I think there are more up-to-date versions than this one. @liwei899 could you please point Stephanie to the right one to look at? Thanks.

**Comment by liwei899** [comment]
> @stepmalt I think there are more up-to-date versions than this one. @liwei899 could you please point Stephanie to the right one to look at? Thanks.

Hi Sean and Stephanie, 
Every version is in the same figma file here https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=93%3A1310&mode=design&t=LCv5C93UNL9QnFhW-1 . @stepmalt Please see the latest version in the file -- handoff. Feel free to leave any feedback on that. 
I haven't updated on this Github page but did sent weekly update until Nov 26 before the user testing. I will update later on this page for the record.

**Comment by stepmalt** [comment]
Made comments via Figma! Will discuss in UXW meeting about a phrasing I'm debating.

@kmuir1991 @jikim322 @tydesignit - tagging you here for later. Want your opinions on the "nuances" wording.

**Comment by kmuir1991** [comment]
Thanks @stepmalt !

@liwei899 for clarity's sake, when you say "see the latest version in the file -- handoff" are you referring to [this page?](https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=551-10773&mode=design&t=uvYXIS4a3LW3c3pG-0)

I want to make sure we're all looking at the right file :)

**Comment by liwei899** [comment]
> Thanks [@stepmalt](https://github.com/stepmalt) !
> 
> [@liwei899](https://github.com/liwei899) for clarity's sake, when you say "see the latest version in the file -- handoff" are you referring to [this page?](https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=551-10773&mode=design&t=uvYXIS4a3LW3c3pG-0)
> 
> I want to make sure we're all looking at the right file :)

Hi @kmuir1991 @stepmalt , please review the copy in Version 13 here https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=637%3A4538&mode=design&t=9uTgZKeKeemz0pgq-1 
Hi @seanlip  Can you check out the new design iterations based on our previous discussions when you have time? Thank you.

**Comment by kmuir1991** [comment]
@liwei899 thank you! Design itself looks great from my end. However, for some reason, the copy updates that were discussed and signed off on during the last round of feedback from UXW were not implemented.

I left a few comments on the design providing that copy again. Please implement that when you have the chance, thank you :)

**Comment by seanlip** [comment]
Thanks @liwei899 -- took a pass!

**Comment by liwei899** [comment]
@kmuir1991 @stepmalt Hi Kate and Stephanie, please check this[ prototype for UXW approval. Thank you.[https://www.figma.com/proto/VlT6bJqNQkH2H18ERvXGIk/Oppia?page-id=720%3A11182&type=design&node-id=720-11185&viewport=831%2C686%2C0.4&t=C1wHKRCQbZWOx62Z-1&scaling=min-zoom&starting-point-node-id=720%3A11185&show-proto-sidebar=1&mode=design](url)
You can also view the mockup in Version 14 from this file[https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=720%3A11182&mode=design&t=o8hKbRos2HliTbaG-1](url)
Thank you.

**Comment by kmuir1991** [comment]
Hi @liwei899 ! I'm a bit confused, as none of the copy that was previously agreed upon has been implemented. It also appears as though the web pop-up copy has been reverted to a previous version.

If you'd like to give me access to the figma as an editor (kate.muir@outlook.com), I can make those updates myself. Let me know, thanks!

**Comment by liwei899** [comment]
I just added you as an editor. By the way, I revised based on Stephanie's
previous comments. Thanks.

**Comment by kmuir1991** [comment]
@liwei899 thank you! I made the updates to version 14.

**Comment by liwei899** [comment]
Awesome, thanks!

**Comment by liwei899** [comment]
@kmuir1991 @stepmalt Hi Kate and Stephanie,

Could you please approve this once you've finished reviewing the copy? After that, I'll pass it on to Sean for final approval. Thank you.

**Comment by kmuir1991** [comment]
@liwei899 done!

**Comment by liwei899** [comment]
> [@liwei899](https://github.com/liwei899) done!

Thank you.

**Comment by liwei899** [comment]
@seanlip Hi Sean, please check this prototype for PM approval. Thank you.[https://www.figma.com/proto/VlT6bJqNQkH2H18ERvXGIk/Oppia?page-id=720%3A11182&type=design&node-id=720-11185&viewport=831%2C686%2C0.4&t=C1wHKRCQbZWOx62Z-1&scaling=min-zoom&starting-point-node-id=720%3A11185&show-proto-sidebar=1&mode=design](https://github.com/orgs/oppia/projects/7/views/url)
You can also view the mockup in Version 14 from this file[https://www.figma.com/file/VlT6bJqNQkH2H18ERvXGIk/Oppia?type=design&node-id=720%3A11182&mode=design&t=o8hKbRos2HliTbaG-1](https://github.com/orgs/oppia/projects/7/views/url)
Thank you.

**Comment by seanlip** [comment]
Thanks @liwei899 ! Just a small note, clicking on your links seems to go to the wrong place. Do you know why this is? If you're using Markdown, make sure that the part of the link inside the parentheses `(...)` has the right destination.

I'll take a look at the prototypes. Thanks!

(Update: I think the mocks look good, just some small fixes to make and then you should be able to hand off. Thanks!)

**Comment by liwei899** [comment]
> Thanks @liwei899 ! Just a small note, clicking on your links seems to go to the wrong place. Do you know why this is? If you're using Markdown, make sure that the part of the link inside the parentheses `(...)` has the right destination.
> 
> I'll take a look at the prototypes. Thanks!
> 
> (Update: I think the mocks look good, just some small fixes to make and then you should be able to hand off. Thanks!)

[https://www.figma.com/proto/VlT6bJqNQkH2H18ERvXGIk/Oppia?page-id=720%3A11182&type=design&node-id=720-11185&viewport=673%2C639%2C0.16&t=FH2RxxFsBN6CjmRJ-1&scaling=min-zoom&starting-point-node-id=720%3A11185&show-proto-sidebar=1&mode=design](url)
Sorry about that. Here is the link

**Comment by liwei899** [comment]
I also change the status to " Hand off to Dev". Thank you.

**Comment by seanlip** [comment]
Thanks @liwei899. Sorry, one more comment in the mocks (just to make sure things are clear for devs), PTAL.

Also one process note -- you should actually change to **"Handed off to PM"** for things that are still wiating to be approved by PM (like this one). Otherwise what's going to happen is that the PM will never file it for devs because they don't see it in their [queue](https://github.com/orgs/oppia/projects/7/views/15)!

**Comment by liwei899** [comment]
Thanks for clarifying on this.  I'll make the necessary adjustment to
ensure clarity for the developers and update the process note accordingly.
I'll let you know when I'm done. Appreciate your guidance on this!

**Comment by liwei899** [comment]
> Thanks @liwei899. Sorry, one more comment in the mocks (just to make sure things are clear for devs), PTAL.
> 
> Also one process note -- you should actually change to **"Handed off to PM"** for things that are still wiating to be approved by PM (like this one). Otherwise what's going to happen is that the PM will never file it for devs because they don't see it in their [queue](https://github.com/orgs/oppia/projects/7/views/15)!

Hi Sean, 
I just revised the Figma file page name and add an additional state to the dev team. Let me know if there is anything else I need to do. Thank you.

**Comment by seanlip** [comment]
Thanks @liwei899! Only one more thing, please update the previous "handoff" pages so that there is only one page in the entire Figma file that has "handoff" in the title. Otherwise it will still be confusing because the dev then sees both the old and the new handoff pages, which differ.

Otherwise I think there's nothing else, thanks!

**Comment by seanlip** [comment]
Thanks @liwei899 -- this has been approved and handed off to the dev team. Filed as https://github.com/oppia/oppia/issues/16164.

Congratulations on finalizing the designs for this project!

**Comment by liwei899** [comment]
Thank you so much Sean.
