### ISSUE TITLE
Redesign of Practice Session and Topic Page

### ISSUE THREAD

**Issue by juliafalarini** [oppia/design-team#97]
**Platform**
Oppia Web

**Describe the request**
This project is about making the Practice Session experience more engaging, and aligned with the learners' learning goals, while also making sure that it is discoverable in the onboarding flow, specifically focusing on the Topic Pages, Lesson Player and Learner Dashboard.

**Context for the request**
We aim to enable learners to navigate easily to the lessons, practice questions, and revision cards, comprehending how each component fits into their overall learning journey. 

**Link to PRD**
[PRD: Practice Session and Topic Page
](https://docs.google.com/document/d/1r9IEQ5z_t-eu9XAWN3eRA7iKdKuYsOQbVUjO2ZH1qKg/edit?usp=sharing)

**Link to Figma File**
[Figma](https://www.figma.com/file/pe0Q3Zx9j6Lt9cvgC7FOOV/Practice-Session-and-Topic-Page---Project-3?type=design&node-id=191%3A19112&mode=design&t=0elMSM3wfQ1B9vGG-1)

**Information about deadlines/priorities**
This project should be completed by December, 8, according to this [timeline](https://docs.google.com/spreadsheets/d/1ODnu5sh9YnV0BQWviRgqkBUyiz10ToDN2DkQyr960kw/edit?usp=sharing).

By Sep, 6 - Create Prototype for the Practice Session experience and Research Plan for the LFT conduct tests with users
By Sep, 22 -  Collect results from LFT
By Sep, 22 -  Create Prototype for the Topic Page, Lesson Player and Learner Dashboard for the LFT conduct tests with users
By Oct, 6 - Collect Results from LFT
By Nov, 3 - Send High-Fi mocks for review
Nov, 3 - Nov, 20 - Possibly another round of tests to validate specific remaining issues
By Dec, 8 - Handoff + Final approval from leads

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [x] UX Design approved
- [x] UX Writing approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (it's enough to have one signoff from each of UXD, UXW and PM):_
- LaCE projects: @ConorMack (UXD), @jikim322 / @roxanashirazi (UXW), @seanlip (PM)

**Comment by juliafalarini** [comment]
Project update:

Complete:

- Lo-fi prototypes 
- [Research Plan 1: Practice Session Experience
](https://docs.google.com/document/d/139bmSJoAeslzcSz0EhCnj_pT8B9yknqJkt5rAzWlqHQ/edit?usp=sharing)
- [Research Plan 2: for Topic Page + Learner Dashboard + Lesson player.](https://docs.google.com/document/d/1nd7h2xb9bmdlJmePbL_GpYEKvZT78fZvtIGt0r3L8Xg/edit?usp=sharing) 
- Ria and Pretty conducted tests and submitted reports for research plan 1.
- Pretty submitted reports for research plan 2.

In progress/Pending:
- I've been meeting with the UXW to discuss and fix issues encountered in the results of the first tests, according to the reports submitted by Ria and Pretty.  
- Reports for the Topic Page Research Plan from Ria.
- I've started consolidating the results of the research plan 2.

Next:
- Finalize consolidation of all results
- Discuss issues with UXW and update mocks accordingly
- Get feedbacks about the updated mocks from UXD team.
- Finalize Hi-Fi mocks by Nov, 3rd.

**Comment by juliafalarini** [comment]
Project Update:

I've finished addressing all comments from Handoff, and I would like to request final approval from leads, so we can finalize this project. @kmuir1991 @seanlip @ConorMack @liwei899 

Thanks

**Comment by kmuir1991** [comment]
@juliafalarini approved!

**Comment by seanlip** [comment]
@liwei899 @ConorMack Could you PTAL at this so that we can hand it off to PM (if everything looks fine)?

@juliafalarini Could you please also link to a folder with all the assets that developers need to implement this project?

Thanks!

**Comment by liwei899** [comment]
Hi Sean,

I responded to Julia’s email yesterday for approval, and I’ve attached a
screenshot for your reference. Could you please clarify the protocol for
approvals? Should we use Github or reply directly to the email? Thanks.

**Comment by seanlip** [comment]
Hi @liwei899, the approval should always be recorded on GitHub at the minimum.  There is a set of checkboxes in the first post of the issue thread that the leads can check off. When both UXD and UXW have approved, the status of the issue should be set to "Handed off to PM".

Does that help?

**Comment by liwei899** [comment]
> Hi @liwei899, the approval should always be recorded on GitHub at the minimum. There is a set of checkboxes in the first post of the issue thread that the leads can check off. When both UXD and UXW have approved, the status of the issue should be set to "Handed off to PM".
> 
> Does that help?

Got it. Thanks for the clarification.

**Comment by liwei899** [comment]
> @liwei899 @ConorMack Could you PTAL at this so that we can hand it off to PM (if everything looks fine)?
> 
> @juliafalarini Could you please also link to a folder with all the assets that developers need to implement this project?
> 
> Thanks!

Hi @juliafalarini , approved. Thanks for your great work.

**Comment by juliafalarini** [comment]
@seanlip the folder with the assets: https://drive.google.com/drive/folders/1W3ZlXP2b6UNL1UURjeuep_xzP8Q1VSjY?usp=sharing

Just a note: all assets can be easily downloaded from Figma, by clicking on them and then, export > svg. 

Thanks!

**Comment by seanlip** [comment]
I have split this into two features and filed them on the web repo at https://github.com/oppia/oppia/issues/19613 and https://github.com/oppia/oppia/issues/19614. Thanks @juliafalarini for your work on these mocks!
